### ISSUE TITLE
minor mis-naming/cut-n-paste error?

### ISSUE THREAD

**Issue by client9** [expressjs/morgan#100]
hello, just noticed the following..

```javascript
/**
 * response header
 */

morgan.token('res', function getResponseTime(req, res, field) {
  if (!res._header) {
    return undefined

```

I think the quasi-fake function name should be `getResponseHeader` not `getResponseTime`

thanks!

n

**Comment by dougwilson** [comment]
Yep, a copy-and-paste error :)
