### ISSUE TITLE
HTTP/2 logged as HTTP 1.1

### ISSUE THREAD

**Issue by receptor** [expressjs/morgan#113]
Using Node v6.2.2 with http2 v3.3.4 express v4.14.0, morgan v1.7.0

```
'use strict'

const express = require('express')
const favicon = require('serve-favicon')
const app = express()
const spdy = require('spdy')
const fs = require('fs')
const morgan = require('morgan')

const options = {
	key: fs.readFileSync(__dirname + '/snakeoil.key'),
	cert: fs.readFileSync(__dirname + '/snakeoil.crt')
};

function handler(req, res)
{
	console.log('HTTP/2', req.isSpdy, 'version', req.spdyVersion)
	
	res.push('/main.js',
		{
			request:
			{
				accept: '*/\*'
			},
			response:
			{
				'content-type': 'application/javascript'
			}
		})
		.end('console.log("Hello World");')

	res.writeHead(200)
	res.end('<script src="/main.js"></script>')
}

app.use(morgan('combined'))
app.use(favicon(__dirname + '/favicon.ico'))
app.get('/', handler)

const server = spdy.createServer(options, app)
server.listen(8000)
console.log('HTTP/2 Server, listening on port 8000')
```

For an HTTP/2 request, this will log:
HTTP/2 true version 4
::ffff:10.1.0.11 - - [01/Jul/2016:13:53:41 +0000] "GET / HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

Looks like Morgan doesn't recognize HTTP/2 requests

**Comment by dougwilson** [comment]
Hi! This is a problem with whatever HTTP server you are using, not Morgan. You can see our code here: https://github.com/expressjs/morgan/blob/master/index.js#L301-L303

All we do is report the `req.httpVersionMajor` and the `req.httpVersionMinor` properties, so it sounds like your server is populating those properties incorrectly. If I set those two 2 and 0, then Morgan properly prints the log as HTTP/2.0.

**Comment by dougwilson** [comment]
Also, I would look into the server, but in your report you said you are using the http2 module, but in your example, you are instead using the spdy module. Which one are you actually using?

**Comment by receptor** [comment]
I've experimented with both http2 and spdy, sorry for the mismatch. The example above uses spdy v3.3.3

Indeed, with spdy it's enough to do this:

```
morgan.token('http-version', function getHttpVersionToken(req)
{
	return req.isSpdy ? '2' : req.httpVersionMajor + '.' + req.httpVersionMinor
})
```

I guess spdy and http2 modules don't adjust req.httpVersion fields. I should open issue with them!

Thanks for the lightning-fast response!

**Comment by dougwilson** [comment]
No problem! Yea, they should probably add that, as it is part of the public API for `req` in Node.js (https://nodejs.org/api/http.html#http_message_httpversion). You're always welcome to override any token in this module to provide your own implements as necessary as well. Of course, saying that SPDY is HTTP/2.0 is a really gray area, as the SPDY protocol is not even compatible with the HTTP/2.0 protocol...
