### ISSUE TITLE
how to set ip from nginx

### ISSUE THREAD

**Issue by r3wt** [expressjs/morgan#114]
i am passing the header as `X-REAL-IP` i log the headers to confirm its there. i then set req.ip as the specified value. but when morgan log runs, there is no ip. why?

```js
// 6. set ip from nginx
app.use(function(req,res,next){
	log.info(req.headers);
	req.ip = req.headers['x-real-ip'] || req.headers['x-forwarded-for'] || req.connection.remoteAddress;
	next();
});

// 7. morgan request logger.
app.use(
	morgan('combined')
);
```

**Comment by Destreyf** [comment]
Whatever you're forwarding from probably needs to have expressjs trust.

```javascript
app.set('trust proxy', 'loopback,uniquelocal');
```

**Comment by r3wt** [comment]
@Destreyf no change. still shows localhost ip

**Comment by loganfsmyth** [comment]
Are you sure your assignment to `ip` is working? `req.ip` is a getter in express: https://github.com/expressjs/express/blob/master/lib/request.js#L339

It you haven't marked your file with `use strict` the assignment would just fail silently.

**Comment by r3wt** [comment]
changing header to `x-forwarded-for` fixes the problem

```js
app.enable('trust proxy');
app.set('trust proxy',function(){ return true; });
```

**Comment by cangzhen** [comment]
//获得经过nginx真实ip地址
morgan.token('remote-addr', function (req) {
    return req.headers['x-real-ip'] || req.headers['x-forwarded-for'] || req.connection.remoteAddress;
});

**Comment by cangzhen** [comment]
```
//get real ip if passed by nginx
morgan.token('remote-addr', function (req) {
    return req.headers['x-real-ip'] || req.headers['x-forwarded-for'] || req.connection.remoteAddress;
});
```

**Comment by darvath** [comment]
@cangzhen As of 2018 this still works, but you need to modify the function **getip** of morgan.
This function resides in  **{yourapp}/node_modules/morgan/index.js**

To something like this.

`function getip (req) {
  return req.headers['x-real-ip'] || req.headers['x-forwarded-for'] || 
    req.ip ||
    req._remoteAddress ||
    (req.connection && req.connection.remoteAddress) ||
    undefined
}`
