### ISSUE TITLE
How to set time zone in date format?

### ISSUE THREAD

**Issue by harryge00** [expressjs/morgan#115]
Log by morgan always in `+0000` time zone while my `console.log` can be in +0800 TZ.

**Comment by harryge00** [comment]
I want to set TZ to +0800

**Comment by houifo** [comment]
you can try this :
`morgan.token('realclfdate', function (req, res) {
    var clfmonth = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
];
 var pad2 = function(num) {
  var str = String(num);

  return (str.length === 1 ? '0' : '')
    + str;
};
  var dateTime = new Date();
  var date = dateTime.getDate();
  var hour = dateTime.getHours();
  var mins = dateTime.getMinutes();
  var secs = dateTime.getSeconds();
  var year = dateTime.getFullYear();
  var timezoneofset = dateTime.getTimezoneOffset();
  var sign = timezoneofset > 0 ? '-' : '+';
  timezoneofset = parseInt(Math.abs(timezoneofset)/60);
  var month = clfmonth[dateTime.getUTCMonth()];

  return pad2(date) + '/' + month + '/' + year
    + ':' + pad2(hour) + ':' + pad2(mins) + ':' + pad2(secs)
    + ' '+sign+pad2(timezoneofset)+'00';
});`

and use it with combined log with :
`app.use(morgan(':remote-addr - :remote-user [:realclfdate] ":method :url HTTP/:http-version" :status :res[content-length] ":referrer" ":user-agent"'`
