### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by hybrisCole** [expressjs/morgan#116]
hello, 

how can I track GraphQL mutations and queries using morgan?

Regards,

**Comment by blakeembrey** [comment]
@hybrisCole I think you have the wrong middleware. This module logs HTTP requests. Can you try and elaborate on what you want beyond this? Maybe a link to what you're doing?

**Comment by hybrisCole** [comment]
hey @blakeembrey, sure, afaik graphql is http based, I have something like this:

```
app.use(morgan(':method :url :status :response-time ms'));
  app.use('/graphql', authMiddleware, graphqlHTTP(({ user }, res) => ({
[...]
```

I know the queries/mutations are somewhere in the request headers, everytime I execute it on my app, I see that morgan successfully logs it, i.e.:

```
POST /graphql? 400 52.047 ms
POST /graphql? 200 1072.732 ms
``` 

What I might need, is to set up a formatting that prints graphql operations (that should be present somewhere in the request object I guess).

**Comment by Naoto-Ida** [comment]
@hybrisCole 
I have the same use case. You want to show what the accessor queried, right?
You might want the `combined` option to show the actual `query` parameters.

```js
app.use(morgan('combined'))
app.use('/graphql', authMiddleware, graphqlHTTP(({ user }, res) => ({
[...]
```

**Comment by hybrisCole** [comment]
@Naoto-Ida yeah something like that, but I would prefer to just have the `query` in a pretty print way, without all the other stuff that `combined` gives you

**Comment by blakeembrey** [comment]
So the issue is it's not printing the query string? Are you sure a query string is being sent for the queries you ask about? As far as I can see, the "combined" mode URL is the same as the URL you're using to print. Are you sure it's not just in the body? I find it unlikely that graphQL would use the query string for mutations.

**Comment by blakeembrey** [comment]
I just went through the Relay implementation (assuming that's following the spec) and it definitely does not use a query string that I can see - https://github.com/facebook/relay/tree/master/src/network-layer/default#L91-L128.

**Comment by blakeembrey** [comment]
Logging the body of HTTP requests is kind of out-of-band of this module as it would require buffering the body and different formats, rendering, etc. You should be able to implement your own middleware for this purpose. I'm sure the GraphQL implementation you use may provide some more valuable hooks as well.

**Comment by hybrisCole** [comment]
@blakeembrey thx for the info, guess someway somehow I could use morgan to log my graphql queries, but I'll do it manually then :).

Regards

**Comment by dougwilson** [comment]
Hi @hybrisCole, the only real requirement is that you have something on your `req` or `res` object and then create a token for it. You can add code into your route that does the body parsing that adds a property you can log. For example, I have used this with JSON RPC without issues. If it wanted to log the RPC method, I would add something like `req.rpcMethod = ...` and then create a token like `morgan.token('rpc-method', function (req) { return req.rpcMethod })`.

**Comment by hybrisCole** [comment]
@dougwilson got it, I think that could work, I'll take a look at the docs, thx man

**Comment by hybrisCole** [comment]
So I made it work this way, I only had to add json bodyparser beforehand:
```
morgan.token('graphql-query', (req) => {
    const {query, variables, operationName} = req.body;
    return `GRAPHQL: \nOperation Name: ${operationName} \nQuery: ${query} \nVariables: ${JSON.stringify(variables)}`;
  });
  app.use(bodyParser.json());
  app.use(morgan(':graphql-query'));
```

If you guys see something weird/wrong please let me know,

Regards,

**Comment by richburdon** [comment]
I'd like to log the response also, but can't figure out if morgan has access to it?

https://github.com/expressjs/morgan/issues/32
