### ISSUE TITLE
Feature request: Option to double space output

### ISSUE THREAD

**Issue by alallier** [expressjs/morgan#118]
Sometimes it may be nice to have `morgan` output be double spaced for readability. This is especially true is terminals that aren't very wide resulting in heavy word wrapping making it hard to distinguish between each server request

**Comment by dougwilson** [comment]
Use a transform stream between morgan and your stdout. This wouldn't be a feature specifically added, since it is already possible using the generic stream interface we already provide, exactly to support these requests :)

**Comment by dougwilson** [comment]
Very simple method:
```js
var morgan = require('morgan')
var split = require('split')

// ... later
app.use(morgan('combined', {
  stream: split().on('data', function (line) {
    process.stdout.write(line + '\n\n')
  })
}))
```

**Comment by alallier** [comment]
Ah very cool! Thank you for pointing this out and the quick reply!
