### ISSUE TITLE
Ignoring specific HTTP endpoint (like health check endpoints)

### ISSUE THREAD

**Issue by hijklmno** [expressjs/morgan#119]
Hi,

Awesome middleware! Able to solve a handful of hard to pin down issues in production! Keep it up!

Right now I have a health check endpoint I defined as `app.get('/health', handle)`. Is it possible to hide this from logs?

Thanks!

**Comment by dougwilson** [comment]
You can either `app.use` this module after your health check route, or use the `skip` option to return `true` for that route (docs for skip option: https://github.com/expressjs/morgan#skip).

**Comment by hijklmno** [comment]
Skip works! Perfect! I implemented skip for that specific route via req.url with this code:

`app.use(logger(config['morgan.debug.level'], {
	skip: function (req, res) {
		if (req.url == '/health') {
			return true;
		} else {
			return false;
		}
	}
}));`

Thank you @dougwilson! Closing.

**Comment by dougwilson** [comment]
No problem :)

**Comment by victorboissiere** [comment]
Great @hijklmno ! This is exactly what I needed!
I think you can simplify it:
```js
app.use(logger(config['morgan.debug.level'], {
  skip: (req, res) => req.url === '/health'
}));
```

**Comment by johnjayasingh** [comment]
I use this
app.use(
  logger("dev", {
    skip: (req, res) => req.url.indexOf("exchange") > -1
  })
);
