### ISSUE TITLE
Create Permission With Morgan?

### ISSUE THREAD

**Issue by crizzs** [expressjs/morgan#120]
Currently, I am running my express app on a Linux server. However, my node app doesn't have permission to either create file or folder. Is there a function in morgan that allows me to chmod for this particular operation?

Regards,
crizzs

**Comment by dougwilson** [comment]
Hi @crizzs, this module, `morgan`, does not provide any type of file operation, even writing to a file. This module simple writes the logs to the steam you provide as the `stream` option on constructions.

**Comment by crizzs** [comment]
Thanks pal.
I managed to resolve it (Modified the file-stream-rotator). It has nothing to with morgan's functionality. 👍
