### ISSUE TITLE
you forgot ALL of your semicolons

### ISSUE THREAD

**Issue by Narvey** [expressjs/morgan#129]
You forgot **all** of your semicolons in README.md examples.

**Comment by blakeembrey** [comment]
It's valid JavaScript following https://github.com/feross/standard. It wasn't forgotten.

**Comment by blakeembrey** [comment]
See the latest commit which follows that style: https://github.com/expressjs/morgan/commit/1533cdcc512f4daf20a93cb0ab3b18d6563a897f.
