### ISSUE TITLE
Question - Stream to stdout or stderr based on status code

### ISSUE THREAD

**Issue by jyotman94** [expressjs/morgan#134]
Is it possible to stream all the status code above 400 to process.stderr and below 400 to process.stdout?

Basically logging to two different files depending on the status code.

**Comment by dougwilson** [comment]
Yes, just put two morgan instances: One with the stdout stream and the skip set to what you don't want there and the other with stderr stream and the inverse skip.

**Comment by jyotman94** [comment]
Oh right makes sense. Thanks!

**Comment by dougwilson** [comment]
No problem! Let me know if you want an example; I didn't right now because I wanted to reply at first from a phone :)

**Comment by jyotman94** [comment]
Its cool, I understood. I''ll paste the code I'm using successfully - 

```
app.use(morgan('combined', {
    skip: function (req, res) {
        return res.statusCode < 400
    }, stream: process.stderr
}));
app.use(morgan('combined', {
    skip: function (req, res) {
        return res.statusCode >= 400
    }, stream: process.stdout
}));
```
