### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by jyotman94** [expressjs/morgan#135]
Updating the following dependencies - 

**dependencies**

- [x] basic-auth 1.0.4 --> 1.1.0
- [x] debug 2.2.0 --> 2.6.0

**devDependencies**

- [ ] mocha 2.5.3 --> 3.2.0
- [ ] supertest 1.1.0 --> 3.0.0

I was able to update all these dependencies to their respective latest version locally and was able to successfully execute all the tests.

**Comment by dougwilson** [comment]
Hi @jyotman94 thanks for the ping :) Apparently I never pushed up some commits I made locally back in December and I updated the `debug` again as well to 2.6.0. The development dependencies only matter for Travis CI / development and unfortunately they are pinned to the last version that run on Node.js 0.8, a platform this module still supports. When the next major version of this module is released and the minimum Node.js version is changed, we can revisit updating those development dependencies :) !
