### ISSUE TITLE
Custom format with colored status

### ISSUE THREAD

**Issue by jonas-arkulpa** [expressjs/morgan#136]
We try to use the dev format with an additional date token.
Is it possible to highlight the status in a custom format?

:method :url :status :response-time ms - :res[content-length]
![image](https://cloud.githubusercontent.com/assets/17269256/22774905/8c675a86-eea9-11e6-93ce-cc955b961969.png)
dev
![image](https://cloud.githubusercontent.com/assets/17269256/22774895/7f336dfa-eea9-11e6-8a7d-071d3c3be528.png)

**Comment by dougwilson** [comment]
The `dev` format is effectively 5 different formats dynamically chosen by the status value. You can see the implementation in the source: https://github.com/expressjs/morgan/blob/master/index.js#L183-L206

The first argument of `morgan()` can be a function, including that function where you tweaked it to add the extra token.

**Comment by josduj** [comment]
To anyone still looking for this, a kinda hacky way to do it is to overwrite existing token.
```javascript
morgan.token('method', req => 'foo ' + req.method)
```
