### ISSUE TITLE
Splitting responses to console.log, console.error

### ISSUE THREAD

**Issue by OmgImAlexis** [expressjs/morgan#139]
Is there an easy way to split the logger between console.log and console.error depending on the HTTP code?

I'd like to use this with winston so I can easily split the 4xx, 5xx, etc. codes to the error logger and the 2xx to the info logger.

**Comment by dougwilson** [comment]
Yep! #134

**Comment by OmgImAlexis** [comment]
Sorry for the simple questions but I didn't see any way of using something like winston instead of a stream.

In the example is there a way to replace the `process.stderr` and `process.stdout` with `log.error()` and `log.info()`? They work similarly to `console.error()` and `console.log()`.

```
app.use(morgan('combined', {
    skip: function (req, res) {
        return res.statusCode < 400
    }, stream: process.stderr
}));
app.use(morgan('combined', {
    skip: function (req, res) {
        return res.statusCode >= 400
    }, stream: process.stdout
}));
```

**Comment by dougwilson** [comment]
You could use the `split` module to construct a simple stream into Winston, if I'm understanding Winston correctly:
```js
var split = require('split')
var winston = require('winston')

var logger = new winston.Logger()
var stream = split().on('data', (log) => logger.log(log))

app.use(morgan('combined', { stream: stream }))
```

**Comment by OmgImAlexis** [comment]
For anyone that stumbles onto this here's an example.

```
app.use(morgan('combined', {
    skip: (req, res) => {
        return res.statusCode < 400;
    }, stream: split().on('data', data => log.info(data))
}));
app.use(morgan('combined', {
    skip: (req, res) => {
        return res.statusCode >= 400;
    }, stream: split().on('data', data => log.error(data))
}));
```
