### ISSUE TITLE
Feature Request: Log on request and response

### ISSUE THREAD

**Issue by Undistraction** [expressjs/morgan#149]
Please add option to log on both request and response.

With long running server-processes it would be useful to see both when a request arrived and when the response was sent. The `immediate` option allows the former and and default behaviour allows the latter, but not both at the same time.

**Comment by dougwilson** [comment]
Just add the middleware twice: one with immediate and one without.

**Comment by Undistraction** [comment]
Of course! Thankyou.

**Comment by dougwilson** [comment]
No problem! You can then have a different format for them. I do that as well in one of my projects :)

**Comment by Undistraction** [comment]
Would be handy to add this suggestion to the README as I don't think this is immediately obvious, but then my experience with Express middleware is minimal.

**Comment by glebec** [comment]
@Undistraction you may also be interested in https://github.com/glebec/volleyball which I wrote for this purpose. It not only logs on both req & res, but assigns each cycle a unique & color-coded ID to make it clear which responses are for which requests.

You can of course manually implement something similar for Morgan; also, Volleyball is a bit of a small simple toy and doesn't have nearly the feature set or support that Morgan does. So for production or special use cases I'd still use Morgan. But for small local dev you might enjoy Volleyball.
