### ISSUE TITLE
Chrome devtool and Morgan

### ISSUE THREAD

**Issue by Subwater** [expressjs/morgan#150]
Morgan doesn't print to devtool console.  I have tried the standalone devtool package from npm, as well as the nodejs inspector through chrome.  No output at all.

I can confirm that in the same script instance `console.log()` will work.

**Comment by dougwilson** [comment]
Hi @Subwater this module [outputs to process.stdout by default](https://github.com/expressjs/morgan#stream), which is different from console.log. You can always provide a `stream` object that will write the streaming log data using `console.log` if you like, though :)

**Comment by Subwater** [comment]
I beg to differ, good sir.

**console.log()**
> Prints to stdout with newline. Multiple arguments can be passed, with the first used as the primary message and all additional used as substitution values similar to printf(3) (the arguments are all passed to util.format()). 

Taken from [Nodejs 6.x Console API](https://nodejs.org/dist/latest-v6.x/docs/api/console.html#console_console_log_data_args)
