### ISSUE TITLE
Security Vulnerability in v1.8.0

### ISSUE THREAD

**Issue by prateekagr98** [expressjs/morgan#151]
#### About the issue
https://nodesecurity.io/advisories/534

**Comment by dougwilson** [comment]
The debug version 2.6.9 is not vulnerable.

**Comment by dougwilson** [comment]
Looking back at this issue, I realize you said version 1.8.0. Yes, upgrade to version 1.9.0 for the fix. Sorry I read your message as 1.9.0 incorrectly.
