### ISSUE TITLE
What is the meaning of the colour codes when a server is started in dev mode?

### ISSUE THREAD

**Issue by leoyli** [expressjs/morgan#154]
Hi,

I just wonder what is the meaning of the colour codes when a server is started (in dev mode)?

It was coloured in grass green showing something like `project-name:server Listening on port 3000 +0ms` in my console at all time.  However, the colour was changed to 'red' or 'blue', or even 'grass green' when I extend methods in `String.prototype` in my app.js file.  The colour is depended on how many methods I was adding in..., which confused me.  I thought I have some errors at beginning to see the red, but how about the blue?

Also it is that something we are expecting? or it is a bug?

note.
added 0 method -> green;
added 1 method -> blue;
added 2 methods -> green;
added 3-5 methods -> red;
...
added 6th method -> green;
added 7th method -> blue;
added 8th method -> green;
added 9th methods -> red;
... (pattern repeats)

**Comment by dougwilson** [comment]
I'm not sure what you mean. As far as I know there is no code in this module that does that. Can you point me to the code you are asking about?

**Comment by leoyli** [comment]
Oh... I'm sorry, it seems that I'm posting this issue at the wrong place.  That issue is from my IDE(webstorm), not from morgan.
