### ISSUE TITLE
:req[headers] or :req[header] return "-" 

### ISSUE THREAD

**Issue by mike-aungsan** [expressjs/morgan#155]
morganFormat = ":date[iso] :remote-addr :remote-user :method :url :req[header] :http-version :referrer :user-agent"

app.use(morgan(morganFormat, {
    immediate: true,
    stream: logger
}))

**Comment by dougwilson** [comment]
Hi! Not dute what the question and/or issue is. Can you elaborate?

**Comment by mike-aungsan** [comment]
This is what I get in the log for this this format ":date[iso] :remote-addr :remote-user :method :url :req[header] :http-version :referrer :user-agent"

2017-11-07T21:50:57.010Z ::ffff:10.64.0.150 - GET / - 1.0 https://www.domain.com/ Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

Do you see req[header] return just dash "-"

**Comment by dougwilson** [comment]
Normally there is no property req.header so you get a dash. What does console.dir(req.header) print for that request?

**Comment by dougwilson** [comment]
Sorry, I'm on a phone and that didn't come out right. I mean normally there is no request header named header. What dkes console.dir(req.headers.header) print? Ade you sending the header "header" in your above request?

**Comment by mike-aungsan** [comment]
But in the doc: https://github.com/expressjs/morgan#reqheader

**Comment by dougwilson** [comment]
Right. It will shoe you the value of the header name you gave in the request. You put "header" as the name. If your request doesnt have the header named header, it will display a dash. Can you show all the request headers that are in your request?

**Comment by mike-aungsan** [comment]
I see. Doc is misleading I would say. Thanks

**Comment by dougwilson** [comment]
Doc improvements are definitely welcome! If you have a better way to word it, please feel free to make a pull request :+1:

**Comment by jwerre** [comment]
Is there a way to display all the request headers? I suppose you would have to `stringify` them somehow or `req.headers` would just turn out like '[object Object]'

**Comment by ryhinchey** [comment]
@jwerre adding your own token function like you did should do the trick! Then all you have to do is:

`app.use(morgan(':request-headers'))`
