### ISSUE TITLE
How to get log string?

### ISSUE THREAD

**Issue by mafeifan** [expressjs/morgan#159]
hi all ,  I want to ask a question about morgan.
I want to pass the log string like ("POST /?platformId=1&key=3&actionType=InputGift 200")  as request data parameter and send to other service instead of putting into files or console.
```javascript
var request = require('request');
var options = {
    url: 'http://192.168.100.16:9700',
    method: 'POST',
   // TODO how to get it?
    body: logString
};
request(options, callback);
```
how can I get the log string?
thanks in advance

**Comment by dougwilson** [comment]
Hi @mafeifan to capture the logs, just provide a Stream as the `stream` option (https://github.com/expressjs/morgan#stream). If you want every log line to generate one request, here is a very simple stream example:
```js
var request = require('request')
var split = require('split')

var httpLogStream = split().on('data', function (line) {
  request({
    url: 'http://192.168.100.16:9700',
    method: 'POST',
    body: line
  })
})

app.use(morgan('common', {
  stream: httpLogStream
}))
```
