### ISSUE TITLE
Is it possible to filter parameters like tokens or passwords?

### ISSUE THREAD

**Issue by Hirurg103** [expressjs/morgan#162]
It would be good to obscure some sensitive information in the logs like passwords or tokens like this:

```
2018-04-17T15:24:40.321: #cbc52742 Started POST /api/method?username=me&password=[FILTERED] for 8.8.9.9
```

Is it possible to configure morgan to filter parameters? Thanks!

**Comment by dougwilson** [comment]
Yep! Just define your own token (or even re-define the `:url` token) to do the filtering and return the filtered string 👍

**Comment by Hirurg103** [comment]
Ok, thank you @dougwilson . I will try to define it in a few days, please do not close this issue for a while

**Comment by Hirurg103** [comment]
Closing this issue for now as I am not going to work with the logs in the near future
