### ISSUE TITLE
Inconsistent defaults and deprecation messages

### ISSUE THREAD

**Issue by javierfernandes** [expressjs/morgan#163]
Hi guys !

This is probably a really tiny not-too-imporant bug, but well.. just found it and I think that it could help others.

Setting up express with morgan in this way

```js
const app = express()
app.use(morgan)
```

Gives this deprecation warning (when trying to log a request, not at start up)

```bash
morgan deprecated morgan(options): use morgan("default", options) instead node_modules/express/lib/router/layer.js:95:5
morgan deprecated default format: use combined format node_modules/express/lib/router/layer.js:95:5
```

It is of course wrong, but I believe it was "the old way". 
Anyway notice there that id proposes you to use `default`  (`use morgan("default", options)`)

But this is in turn deprecated, so if you change it like that you will get another deprecation message

```js
const app = express()
app.use(morgan('default'))
```
You get

```bash
morgan deprecated default format: use combined format index.js:30:30
```

So, I believe that the first message should be updated to directly instruct you to use the "combined" option instead of the "default".

Thanks !
Regards !

**Comment by dougwilson** [comment]
So taking a look, I see what happened here and how you ended up with some weird messages. You didn't actually construct the middleware at all in your exanple, passing the factory as a middleware instead of an actual middleware:
```
const app = express()
app.use(morgan()) // note the extra parans
```

The weirdness I'm not sure can be fixed without actually breaking stuff. If you have an idea for how to do it, please feel free to pull request it. It is eluding me, at least.

**Comment by javierfernandes** [comment]
@dougwilson right ! Indeed I was using it wrongly.
So there are 2 different issues here.
1) using it (wrongly) directly as a middelware instead of calling it as a fn to get the middleware
2) this still happens if you call `morgan({})`, that is, with an object as fmt. It shows the outdated message

I've tackled 2) in #164 

And proposed there a way to detect 1) and some doubts on how to handle it.

Please check that PR

Thanks !

Cheers

**Comment by dougwilson** [comment]
Thanks! The PR does the same thing I tried yesterday which doesn't work: the formats default and combined are different.  You can't just suddenly change people's existing code to start using the combined format. That would be a semver major change, in which case all deprecations would be removed as part of any semver major update anyway.

**Comment by Zolw95** [comment]
const morgan = require("morgan");
  app.use(morgan("dev"));

Make sure you're not calling app.use(morgan) anywhere else in your code.
