### ISSUE TITLE
Some requests not getting logged 

### ISSUE THREAD

**Issue by kushubham9** [expressjs/morgan#168]
Hi,
In my application, I am facing a strange issue. I use morgan to log 3 kinds of requests. 
1. Success ( 200 )
2. Failure (non 200)
3. Immediate (immediate req logging)

Now the thing is, there are a couple of instances where a request is getting logged in 'immediate' logs but not in 'failure' or 'success'. 

```
// log only 200 responses to success calls
  app.use(morgan(':requestId :remote-addr - :remote-user [:date[clf]] ":method :url HTTP/:http-version" :status :res[content-length] :response-time ms ":referrer" ":user-agent"', {
    stream: successLogStream,
    skip: function (req, res) {
      return res.statusCode !== 200
    }
  }))

  // log all failed requests to error logs
  app.use(morgan(':requestId :remote-addr - :remote-user [:date[clf]] ":method :url HTTP/:http-version" :status :res[content-length] :response-time ms ":referrer" ":user-agent"', {
    stream: failureLogStream,
    skip: function (req, res) {
      return res.statusCode === 200
    }
  }))

  // log all requests received
  app.use(morgan(':requestId :remote-addr - :remote-user [:date[clf]] ":method :url HTTP/:http-version"', {
    stream: requestLogStream,
    immediate: true
  }))
```

I have observed this behavior when I return 500 status codes. Around 50% of the failures are not getting logged. I am not sure about 2XX or any other status code.

Node version: 9.5.0
Morgan: 1.9.0

**Comment by dougwilson** [comment]
Very strange. I don't see anything off hand wrong in the given code. Is it possible you provide the exact steps to reproduce the issue. i.e. complete code I can run that includes some kind of route that produces a 500 and the request to make that only logs immediate but not the end?

**Comment by kushubham9** [comment]
Cannot share the exact code. But its something like this:
I have an error handler middleware

```
async preErrorHandler (error, req, res, next) {
    const statusCode = error.status ? error.status : 500
    if (statusCode === 500) {
      mylogger.log(error)
    } 

    const response = generateResponse(error)

    return res.status(statusCode).send({
      status: 'failure',
      message: response.error
    })
  }
```

mylogger.log() is logging the event, and I can see them in my logs. But then morgan failure logs have some missing entries. 

My service calls some external HTTP APIs and there is a timeout >10s. In case of such timeouts I am generating 500 error.

**Comment by dougwilson** [comment]
Gotcha. I don't need you exact code, just some code I can simply copy and paste and run without modification (so we are running the same thing to reproduce) and the exact instructions for how to make the call to see the issue happening. Without that, I'm not sure how to figure out what is happening, though you have the conditions on your side, maybe you'd be kind to submit a pull request with a fix  )

**Comment by nemanjapetrovic** [comment]
I'm experiencing the same issue here as @kushubham9 . Did you solve your issue somehow?

**Comment by nemanjapetrovic** [comment]
@dougwilson 

There is a problem @kushubham9 described with morgan package. I test it out with the next packages:

- express: 4.16.4
- morgan: 1.9.1

Here is an example which you can use to test this issue out:

```
const express = require('express');
const app = express();
const morgan = require('morgan');

app.get('/ok', (req, res) => {
    res.status(200);
    res.send('hello world');
});
app.get('/error', (req, res) => {
    throw Error('cannot divide by zero');
});

app.use(morgan('tiny'));

app.listen(3000, () => {
    console.log('New server running on port %s', 3000);
});
```

If you enter:  http://localhost:3000

in a console you will get log:

```
GET / 404 139 - 9.495 ms
GET /favicon.ico 404 150 - 0.816 ms
GET /favicon.ico 404 150 - 0.504 ms
```

but if you enter: http://localhost:3000/ok

**you won't get any log**

same goes for: http://localhost:3000/error

**Comment by dougwilson** [comment]
That is exactly how Express works: you added those routes before the morgan middleware, which stops them from entering morgan. Morgan can only log what goes through it's middleware. Move your app.use of morgan above the two app.get to the top.
