### ISSUE TITLE
Morgan documentation question

### ISSUE THREAD

**Issue by RafaelFreita** [expressjs/morgan#178]
So, this is more of a question than an issues, but i don't know where else to post this, so here we go.

I'm using morgan on a nodejs project and I realized the Intellisense from VScode is showing me some attributes that were not on the index.js file.
After searching for them I realized they were on the README file.

Example: when calling morgan as a function 'morgan()', it shows 7 possibilities of formats.

So my question is: how is that done? What is it called? I found that so cool but I have no clue where starting searching.

Thanks in advance!

**Comment by dougwilson** [comment]
I'm not sure what you mean.

**Comment by RafaelFreita** [comment]
Okay, i'll add a link to an image to better exemplify it.

But that's basically it. I have doubts on how I'm able to see this documentation, which I first assumed would only be visible if that was on the file itself as a JSdoc.

So, after looking into the files, i suppose this come from the README file.

**Comment by dougwilson** [comment]
It's no problem! There really isn't anything here other than what you see in the GitHub repo, and I don't do anything special. It's possible that there is some kind of README scraping going on with that program, not sure.

**Comment by RafaelFreita** [comment]
I totally forgot about pasting the image link, sorry. Here is it:
https://ibb.co/i9MY6K

I tried making a test package copying morgan's structure but had no success with it. I get the default JSdoc (as expected) instead of the readme.

I'm clueless on this one haha

**Comment by RafaelFreita** [comment]
Okay, after a lot of rumbling around:

I tried to change what was written in the README and that didn't change what the Intellisense was showing.

So I started looking once again and I found at 'USER\AppData\Local\Microsoft\TypeScript\2.9\node_modules\@types\morgan" a file index.d.ts which contained the same descriptions that were in the README. When changing it, the description intellisense gave changed!

So, what's that file? Apparently it's a file on (this repo)[https://github.com/DefinitelyTyped/DefinitelyTyped] used to document Typescript projects but seems like it can be used for JS projects too. Now, when it's that downloaded (I suppose NPM does it), why VScode uses it instead of the JSdoc is still a question to me.

Did you know about that or is it news for you? There is a readme there too which contains the github of the users that created this (@type/morgan)[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/morgan] and it seems to me they didn't have anything to do with morgan's development.

I'll close this as I found the source, but I'd like to hear anything you have to say :)

**Comment by dougwilson** [comment]
It's news to me.
