### ISSUE TITLE
What is this at the beginning of log file `::ffff`

### ISSUE THREAD

**Issue by mikeerickson** [expressjs/morgan#179]
I am using the `combined` format for logging.  What does the leading `::ffff` mean

```
::ffff:127.0.0.1 - - [10/Aug/2018:22:58:15 +0000] "POST /graphql? HTTP/1.1" 200 350 "http://localhost:4000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0"
::ffff:127.0.0.1 - - [10/Aug/2018:22:58:16 +0000] "GET / HTTP/1.1" 302 60 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0"
```

**Comment by dougwilson** [comment]
Node.js provides IPs that look like that for whatever reason.

**Comment by dougwilson** [comment]
It's just whatever string that is returned by the Node.js API https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_socket_remoteaddress

**Comment by mikeerickson** [comment]
So, I am assuming `::ffff` is common :)

Thanks!

**Comment by dougwilson** [comment]
It shows up in like all my logs, at least.

**Comment by shaneapen** [comment]
This question is answered here. https://stackoverflow.com/a/49796071/3284379
