### ISSUE TITLE
Why is format set to default, if not given?

### ISSUE THREAD

**Issue by Kamalnrf** [expressjs/morgan#180]
We are having deprecation warning if the format is 'default', my doubt is if the format is not given we can use other formats, why 'default'?

https://github.com/expressjs/morgan/blob/4dd1180260150598657708720c62504bb2200011/index.js#L65

**Comment by dougwilson** [comment]
I don't understand the question.

**Comment by Kamalnrf** [comment]
When you don't pass format like this:
```
app.use(morgan({
    stream: accessLogStream 
}))
```

Log you get for that is this
```
morgan deprecated morgan(options): use morgan("default", options) instead index.js:32:9
morgan deprecated default format: use combined format index.js:32:9
```

We are getting `default` deprecated warning because as there is no format set, we are setting format to default.   

My doubt was why is it set to default instead of other formats?

**Comment by dougwilson** [comment]
You are getting teo deprecations:

(1) you are passing an options argument as the first argument. You need to pass a format as the first argument.

(2) you are not specifying a format in your call. You need to pass a format.
