### ISSUE TITLE
is there a way to pass a 'meta' object to winston through morgan?

### ISSUE THREAD

**Issue by rconstantine** [expressjs/morgan#181]
I'm using Morgan for the HTTP logging and Winston wraps it. There is no explicit link between the two other than setting up the 'stream' option. Winston allows for a 'meta' object that can contain additional fields beyond the message and level. All of my logs except the Morgan ones contain metadata, like the username of the person triggering the leg event (or SYSTEM if not a user), and I'd like to add the same kind of thing for Morgan logs going to Winston. Any ideas?

**Comment by dougwilson** [comment]
So morgan is just a text logger and writes just a string to a stream for each log entry. I'm not sure what you're really talking about, so hard to answer more than that. Perhaps a code example would help clarify.

**Comment by rconstantine** [comment]
OK, that means there's no option. That's OK. The data is still available, I just can't parse it easily. I'll have to consider formatting as JSON. Thanks for the reply.

**Comment by Uko** [comment]
@rconstantine did you find a nice solution? Because I need to log objects (yes, like JS objects, not text), and I'm considering to hack Morgan to be able to specify a function that should be executed for each obtained object. If you know about other solutions it would be nice to learn :)

**Comment by Uko** [comment]
Actually, it's really interesting. If there was no `+ '\n'` in https://github.com/expressjs/morgan/blob/master/index.js#L130 it could be straightforward to do object logging.

**Comment by tonyxiao** [comment]
The simplest solution would be to change this one line

https://github.com/expressjs/morgan/blob/master/index.js#L130

from `stream.write(line + '\n')` to `stream.write(line + '\n', req, res)`. That way additional context related to the request can be passed to the stream object if needed. Would anyone object to a fork?

**Comment by dougwilson** [comment]
Hi @tonyxiao you're certainly welcome to fork it. As far as your proposal goes, the `.write` function takes the values defined by the Node.js stream interface: https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback

That is, the signature is `.write(chunk[, encoding][, callback])`. You would end up passing the `req` object as the `encoding` and the `res` object as the `callback` in your case.
