### ISSUE TITLE
Feature request: ability to select output

### ISSUE THREAD

**Issue by rodrigomata** [expressjs/morgan#183]
Right now Morgan works with process.stdout.write, but these outputs are not displayed in Google Cloud functions logs, only with console.log; therefore, it would be a great addition to select which output mechanism to use, and let process.stdout.write to be the default.

**Comment by dougwilson** [comment]
Just pass a different stream you would like the logs written to by using the stream option:

https://github.com/expressjs/morgan/blob/master/README.md#stream
