### ISSUE TITLE
Inability to pass variables to stream.write function

### ISSUE THREAD

**Issue by xpusostomos** [expressjs/morgan#185]
One problem with morgan logging is that you can't pass variables from the skip function to the stream.write function. So for example, if the skip function examines the situation and wants to set the logging level based on what it discovers, there is no way to pass that decision to the stream.write function. Now I was able to get around this by inserting this decision into the log text, and then parsing it out later, however this is ugly. What would be better if I could store this in the response object, and then have the response object passed to a user definable logger function. So what you would have is the option of instead of defining a stream: parameter you could define a logger: parameter which is similar to stream.write except it is also passed the request and response. Below is the code for how I got around it, but having to split apart the message is ugly.

   const morgan = require('morgan');
    this.expressApp.use(
      morgan(
        ':logLevel :logPrefix :method :url :status :res[content-length] :response-time ms :remote-addr :remote-user',
        {
          stream: {
            write: function(message, encoding) {
              const [level, ...rest] = message.split(' ');
              winston.log(level, rest.join(' ').trim());
            }
          },
          skip: function(req, res) {
            if (currLogConfig.variables.logHttpError && res.statusCode >= 400) {
              //  >=400 http error
              res.logLevel = 'error';
              res.logPrefix = 'httpError';
              return false;
            } else if (
              currLogConfig.variables.logSlow &&
              (!req._startAt ||
              !res._startAt || // null response time = no response, logs "-"
              res._startAt[0] - req._startAt[0] >= currLogConfig.variables.slowDelay)
            ) {
              res.logLevel = 'warn';
              res.logPrefix = 'slow';
              return false;
            } else if (currLogConfig.variables.logAll) {
              res.logLevel = 'info';
              res.logPrefix = 'nodeCall';
              return false;
            }
            return true;
          }
        }
      )
    );
    morgan.token('logLevel', function(req, res) {
      return res.logLevel;
    });
    morgan.token('logPrefix', function(req, res) {
      return res.logPrefix;
    });

**Comment by dougwilson** [comment]
That's because that's a limitation of Node.js streams; there is no method to pass variables to the `.write` method. Here is the signature of that method from the Node.js stream documentation: https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback

> writable.write(chunk[, encoding][, callback])

**Comment by dougwilson** [comment]
For your use-case of wanting to use different streams for different "log levels" you determined based on `req`/`res`, you want to define a separate `morgan` instance for each of your log levels and have you `skip` function return true for requests that do not meet that log level.

Here is an example for multiple morgans in an app: https://github.com/expressjs/morgan#split--dual-logging

**Comment by xpusostomos** [comment]
I thought about using more than one logger, but this solution is not acceptable. Firstly, while morgan logging is reasonably efficient, it's certainly not so efficient that in a production environment I'd be wanting to insert more than one logger. There might be dozens of scenarios I could efficiently deal with in a skip: function, but it would in no way be efficient to insert dozens of loggers.

Secondly, there could be multiple parameters I need to pass, and if you're suggesting a different logger for every combination, the number of loggers could expand exponentially.  For example, in some cases I might want to log to another log entirely at a different log level.

Your comment that that it is a limitation of Node.js streams is nonsense. In fact, morgan doesn't care less if it is passed a stream, all it cares about is it passed a structure that contains a member called write which is a function that takes one string argument. All I'm suggesting is that you provide a different option of logger: which is a structure which contains a function that takes 3 arguments, the string, the request and the response.

Also not cool how quickly you summarily dismissed and closed this issue. Too much arrogance.

**Comment by dougwilson** [comment]
I get it that you would like a different interface than this module provides. That is fine, and there are many loggers out there that work in different ways.

Your comments are not constructive regardless.
