### ISSUE TITLE
Custom logs

### ISSUE THREAD

**Issue by ran-j** [expressjs/morgan#189]
Im using cluster in my app and I would like to print which cluster ID is responding the request in log.

There is a option for this ?

**Comment by dougwilson** [comment]
Indeed. Just specify a custom format for you log to include the value you want to print (https://github.com/expressjs/morgan/blob/master/README.md#morganformat-options) and define a new token that returns that value (https://github.com/expressjs/morgan/blob/master/README.md#creating-new-tokens).
