### ISSUE TITLE
TSR tslint-config-security issue

### ISSUE THREAD

**Issue by dcuenot** [expressjs/morgan#196]
Hello,

When I'm defining a custom formatter with this following code, it's working, however I have an issue regarding "tslint-config-security"

```
morgan(function (tokens, req, res) {
  return [
    tokens.method(req, res),
    tokens.url(req, res),
    tokens.status(req, res),
    tokens.res(req, res, 'content-length'), '-',
    tokens['response-time'](req, res), 'ms'
  ].join(' ')
})
```

The error raised by tslint-config-security is this one:
`
ERROR: /backend/server/common/morganAuditLogger.ts:28:4 - Found unsafe properties access `

How can I fix the issue?

Thanks for the feedback
Damien

**Comment by dougwilson** [comment]
What does the error mean?

**Comment by dcuenot** [comment]
You can have a look to the definition here: https://www.npmjs.com/package/tslint-config-security#tsr-detect-unsafe-properties-access

**Comment by dougwilson** [comment]
I still don't understand. Is it your code above that is doing property access or something?

**Comment by dcuenot** [comment]
this block `tokens['response-time'](req, res), 'ms'` is doing the property access

**Comment by dougwilson** [comment]
Ok. So it sounds like you just need to change that line to something else? I'm not sure if there is something this module can do to change that code.

**Comment by dougwilson** [comment]
If it helps, you can just use the format string option (https://github.com/expressjs/morgan#using-format-string-of-predefined-tokens), which will produce the exact same output as the code you pasted above.
