### ISSUE TITLE
I may be stupid but how do i log the error stack of a 500 internal server error?

### ISSUE THREAD

**Issue by kaizokupuffball** [expressjs/morgan#198]
For now i tried the following

`
app.use(function(error, req, res, next) {
    var errorLogStream = rfs('error.log', { interval: '7d', path: logDir });
    app.use(morgan('combined'));
    res.status(500);
    res.render('errors/500');
});
`

**Comment by joewagner** [comment]
@kaizokupuffball Your formatting is a little weird, but it looks like you are adding a new middleware every time your error handling middleware is called.  This is not how express is designed to work.
the line `app.use(morgan('combined'));` should be moved out of the error middleware.  Usually morgan will be near the beginning of the middleware stack.

**Comment by kaizokupuffball** [comment]
![image](https://user-images.githubusercontent.com/4356128/58731198-6d41e180-83ee-11e9-9d0e-35bfa2f08a39.png) Something like this or am i missunderstanding?

**Comment by joewagner** [comment]
@kaizokupuffball yeah, that looks better.  Does that work how you expect?

**Comment by kaizokupuffball** [comment]
No, unfortunately not. The log file does never contain anything. Looks like it need writes to the file. :-S

**Comment by joewagner** [comment]
@kaizokupuffball if you remove the `stream` option does it log to the console?

**Comment by kaizokupuffball** [comment]
Yea, it logs to the console either way.

**Comment by joewagner** [comment]
@kaizokupuffball I see.  In that case it would seem the issue is with whatever the function `rfs` is returning.  If you can provide a full working example that demonstrated the issue someone can help you figure this out.

**Comment by kaizokupuffball** [comment]
`rfs` is `const rfs = require('rotating-file-stream');`
[https://www.npmjs.com/package/rotating-file-stream](url)

**Comment by joewagner** [comment]
@kaizokupuffball I'm not familiar with that module.  The `stream` option expects an output stream.  Can you double check that your call to `rfs` is returning an output stream?  I have to step away from the computer, but if you can provide a a simple working example it would be a lot easier to help you out when I get back.

**Comment by kaizokupuffball** [comment]
Ill do what i can! :)

**Comment by kaizokupuffball** [comment]
The whole project is here, with a readme file for ease.
https://stuff.darkleaks.net/joewagner/

**Comment by joewagner** [comment]
@kaizokupuffball I had a chance to look at this, and the example you posted logs everything in a file called `access.log`

**Comment by joewagner** [comment]
@kaizokupuffball 
**UPDATE**: I just looked at the readme you included, and I now understand the issue you are having, sorry about the original response.

You want to be using the [skip option](https://github.com/expressjs/morgan#skip) with [dual logging](https://github.com/expressjs/morgan#split--dual-logging).
Assuming you want status less than 400 in the access log and all others in the error log you would do the following:

```
const logDir = 'log';
fs.existsSync(logDir) || fs.mkdirSync(logDir);
var accessLogStream = rfs('access.log', { interval: '7d', path: logDir });
// log less than 400
app.use(morgan('combined', {
    stream: accessLogStream,
    skip: (req, res) => res.statusCode >= 400
}));

var errorLogStream = rfs('error.log', { interval: '7d', path: logDir });
// log greater than or equal to 400
app.use(morgan('combined', {
    stream: errorLogStream,
    skip: (req, res) => res.statusCode < 400
}));
```

Does that work how you are hoping?

**Comment by kaizokupuffball** [comment]
Okay, so I need to use dual logging, that helps a bit actually. But it still doess't quite do what I think off. 
If you use the code and start the server and go on to `http://localhost/auth/login` as there is a premade 500 server error there, you can see that the error is not logged anywhere. I want to log the whole error if you catch my drift. You can also see the manmade error below, that is what i want to log. :)
![image](https://user-images.githubusercontent.com/4356128/58833173-c6a94b00-8650-11e9-81cb-4915a4bbc847.png)

**Comment by joewagner** [comment]
@kaizokupuffball I see, to log the error you will probably want to write [your own formatter](https://github.com/expressjs/morgan#using-a-custom-format-function) as described in the README.md

**Comment by kaizokupuffball** [comment]
Ahh, okay, i'll give that a try then, closing this as that probably is the solution. xD Thank you though!

**Comment by joewagner** [comment]
Awesome, glad to help
