### ISSUE TITLE
In which coordinate system does morgan.js log time?

### ISSUE THREAD

**Issue by IDONTSUDO** [expressjs/morgan#202]
GET /users/ 304 33.804 ms - -
OPTIONS /user/5d06c55a07738d2a60f7655b 204 0.410 ms - 0
GET /user/5d06c55a07738d2a60f7655b 304 10.947 ms - -
OPTIONS /user/5d06c55a07738d2a60f7655b 204 0.408 ms - 0
GET /user/5d06c55a07738d2a60f7655b 304 12.314 ms - -
GET /users/ 304 32.110 ms - 

`32.110 ms how many milliseconds is it?`

**Comment by dougwilson** [comment]
I'm sorry, i don't understand the question. I'm not familiar with a coordinate system for time. 32.110 ms is 32.110 milliseconds.

**Comment by IDONTSUDO** [comment]
Perhaps the question is stupid.

I think it will help you. https://en.wikipedia.org/wiki/Millisecond

But for koa.js / laravel the logger works differently. And I would like to compare their effectiveness.

**Comment by dougwilson** [comment]
Thanks for the link, but it doesn't really clarify to me what you're asking, unfortunately.

**Comment by IDONTSUDO** [comment]
okay, thx
