### ISSUE TITLE
Add support for callback function

### ISSUE THREAD

**Issue by Karamorf** [expressjs/morgan#203]
I've got a use case where I don't want these entries going to a file or STDOUT. I've already got a logging class, I'd highly prefer to send these messages to that class. To solve that, being able to provide a callback function would be ideal. Something like this:
function cb(message) {
   logClass.info(message); //or whatever custom logic to handle the string
}
app.use(morgan('combined', { callback: cb }))

**Comment by dougwilson** [comment]
This is already supported, as this module provides the most generic interface: a stream. Just direct the output of that steam however you like. Here is an example writing with `logClass.info`:
```js
var split = require('split')

var stream = split().on('data', (log) => logClass.info(log))

app.use(morgan('combined', { stream: stream }))
```
