### ISSUE TITLE
Unpredictable undefined status and undefined response time

### ISSUE THREAD

**Issue by Jaeiya** [expressjs/morgan#205]
I was testing my admin panel with 100's of logs for benchmarking and every once in a while, I would get a request object that looked like this:

```json
"req":{"method":"GET","url":"/robots.txt"},"delay":"undefined ms"}
```

I have a custom formatter applied to give me the JSON output:
```typescript
  const display = {
    id      : gen.UID(),
    date    : Date.now(),
    address : tokens['remote-addr'](req, res),
    identity,
    referrer: tokens['referrer'](req, res),
    agent   : tokens['user-agent'](req, res),
    req: {
      method: tokens['method'](req, res),
      status: tokens['status'](req, res),
      url   : tokens['url'](req, res),
      data,
    },
    delay: tokens['response-time'](req, res) + ' ms'
  };
```

As you can see, the request object is missing the status property and contains an undefined response time. I tried to check if this was because I was rapidly adding logs, but no matter how fast or slow I made requests, this would inevitably happen at sporadic intervals.

Any ideas?

**Comment by dougwilson** [comment]
> If the request/response cycle completes before a response was sent to the client (for example, the TCP socket closed prematurely by a client aborting the request), then the status will be empty (displayed as "-" in the log).

Though the way you have it set up, it would be undefined versus the dash, since you're passing through the direct value.

**Comment by Jaeiya** [comment]
Does that mean `tokens['status'](req, res)` will return undefined when this happens?

**Comment by dougwilson** [comment]
Right, if the request/response cycle completes before a response was sent to the client (for example, the TCP socket closed prematurely by a client aborting the request), then the status will be returned as "undefined". This is because there was no response and a status is part of a response.

**Comment by Jaeiya** [comment]
Thank you for the quick response. I guess I can add my own code for undefined status.
