### ISSUE TITLE
How do I log only on POST requests?

### ISSUE THREAD

**Issue by burton666** [expressjs/morgan#208]
I have tried reading the documentation but can't figure out how to only log POST requests.

Right now I am using:

```
morgan.token('person', (request, response) => {
    return JSON.stringify(request.body)
})

app.use(morgan(':method :url :status :res[content-length] - :response-time ms :person'))
```

But it also logs the GET requests.

**Comment by dougwilson** [comment]
You van use the skip option https://github.com/expressjs/morgan/blob/master/README.md#skip to skip logging all non POST requests.
