### ISSUE TITLE
Morgan Skip not working for me 

### ISSUE THREAD

**Issue by N00nDay** [expressjs/morgan#216]
I am attempting to only log errors but I cannot seem to get it to work. Below is my code which matches the code in the documents which is what I am currently using in my code:

```
const app = express();
app.use(
  morgan('combined', {
    skip: function (req, res) { return res.statusCode < 400 }
  })
);
```

This continues to log everything. I am currently using morgan 1.9.1.

**Comment by joewagner** [comment]
@N00nDay Can you post more information or a small piece of code that can be run to reproduce the issue?

**Comment by N00nDay** [comment]
```
require("newrelic");
const sslRedirect = require("heroku-ssl-redirect");
const express = require("express");
const mongoose = require("mongoose");
const bodyParser = require("body-parser");
const morgan = require("morgan");
const keys = require("./config/keys");
const cors = require("cors");
const router = require("./router");
const cluster = require("cluster");
const compression = require("compression");

if (cluster.isMaster) {
  // var numWorkers = require("os").cpus().length;
  var numWorkers = 4;

  console.log("Master cluster setting up " + numWorkers + " workers...");

  for (var i = 0; i < numWorkers; i++) {
    cluster.fork();
  }

  cluster.on("online", function(worker) {
    console.log("Worker " + worker.process.pid + " is online");
  });

  cluster.on("exit", function(worker, code, signal) {
    console.log(
      "Worker " +
        worker.process.pid +
        " died with code: " +
        code +
        ", and signal: " +
        signal
    );
    console.log("Starting a new worker");
    cluster.fork();
  });
} else {
  const app = express();

  if (process.env.NODE_ENV !== "production") {
    app.use(morgan("dev"));
  } else {
    app.use(
      morgan("combined", {
        skip: function(req, res) {
          return res.statusCode < 400;
        }
      })
    );
  }

  app.use(compression());

  mongoose.Promise = global.Promise;
  mongoose
    .connect(keys.mongoURI, {
      useCreateIndex: true,
      useNewUrlParser: true,
      useUnifiedTopology: true
    })
    .then(() => {
      if (process.env.NODE_ENV !== "production") {
        console.log("Connected to Database: " + keys.mongoURI);
      }
    })
    .catch(err => {
      console.log("Error on start: ", err.stack);
      process.exit(1);
    });

  app.use(cors());
  app.use(bodyParser.json({ type: "*/*", extended: true }));

  router(app);

  app.use((err, req, res, next) => {
    res.setHeader(
      "Cache-Control",
      "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    );
    res.status(422).send({ error: err.message });
  });

  app.use(sslRedirect());

  if (process.env.NODE_ENV === "production") {
    const path = require("path");
    // app.use(express.static("client/build"));
    app.use(express.static(path.join(__dirname, "client/build")));

    app.get("*", (req, res) => {
      res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
    });
  }

  const PORT = process.env.PORT || 5000;
  app.listen(PORT, () => {
    console.log("Running on port: ", PORT);
  });
}

```

**Comment by N00nDay** [comment]
Oddly enough:

```
app.use(
      morgan("combined", {
        skip: function(req, res) {
          return res.statusCode < 400;
        }
      })
    );
```
this works on my development server but not on production in heroku.  I have confirmed that the if statement prior to this code is working as expected.

**Comment by joewagner** [comment]
@N00nDay Just a guess here, but can you confirm that `cluster` is setting `process.env.NODE_ENV`?  I.e. setup a `console.log(process.env.NODE_ENV)`  above the conditional where you choose which options to pass to Morgan.

**Comment by N00nDay** [comment]
It is working correctly.  I added a console inside each if/else that was logging "dev" and "prod" and it was logging as expected.

**Comment by dougwilson** [comment]
The check you have is `process.env.NODE_ENV !== "production"`, so if it's `"prod"` then it would still use the non-skip one.

**Comment by N00nDay** [comment]
I can see how that would be confusing.  This is what the test code looked like:

```
if (process.env.NODE_ENV !== "production") {
console.log("dev");
    app.use(morgan("dev"));
  } else {
console.log("prod");
    app.use(
      morgan("combined", {
        skip: function(req, res) {
          return res.statusCode < 400;
        }
      })
    );
  }
```

**Comment by dougwilson** [comment]
is the issue reproducible locally or only on heroku? I'm not familiar with Heroku so have no idea what the differences would be. If you can provide something we can reproduce locally we can debug it.

**Comment by N00nDay** [comment]
Works as expected on development. Heroku does not work.

**Comment by dougwilson** [comment]
Ok. Besides us just making guesses, is there any way we can help resolve this?

**Comment by N00nDay** [comment]
Not trying to make you guess.  I tried stackoverflow first but got zero responses so I thought I would try hear.  I am just looking for some direction since I don't understand why its not working myself.

**Comment by dougwilson** [comment]
Gotcha. I mean, I have no idea why it wouldn't work in Heroku. I would think it would either work everywhere or work no where. What are the differences between the two environments? Maybe we can work though the list of differences to determine what difference may be breaking it? Is it possible to connect a debugger to your Heroku app?

**Comment by N00nDay** [comment]
Well this was a dumb issue.  It was an old user that hadn't updated.  Pushed a forced updated for all users and now the issues seems to be resolved.  My apologies for wasting your time and thank you for attempting to help my idiocy.

**Comment by pierroo** [comment]
> Well this was a dumb issue. It was an old user that hadn't updated. Pushed a forced updated for all users and now the issues seems to be resolved. My apologies for wasting your time and thank you for attempting to help my idiocy.

Hello @N00nDay ,

Actually I am facing the same issue: the skip isn't working on my heroku deployment.

I am using:

app.use(morgan('dev', {
  skip: function (req, res) { return res.statusCode < 400 }
}));   

witout any condition, but it keeps logging every request.

I'm not sure I understood how you solve your issue? :/
