### ISSUE TITLE
TypeError: rfs is not a function

### ISSUE THREAD

**Issue by tharindulucky** [expressjs/morgan#217]
When using `rfs` like this, it throws an error. 

**log file rotation**
```
var accessLogStream = rfs('access.log', {
  interval: '1d', // rotate daily
  path: logDirectory
})
```

Instead, use it like this

```
const accessLogStream = rfs.createStream('access.log', {
    interval: '1d', // rotate daily
    path: logDirectory
});
```

**Comment by drai-cemtrexlabs** [comment]
Thank you. Had same issues.

**Comment by a10kiloham** [comment]
Thanks @tharindulucky that just fixed it for me too

**Comment by ryhinchey** [comment]
added the `docs` label as there's a PR open to update the README to account for the api change in `rfs`

**Comment by Nayan-114** [comment]
But why it gives an error and the letter fixes it
