### ISSUE TITLE
How to dynamically generate morgan token 

### ISSUE THREAD

**Issue by 8801883270** [expressjs/morgan#224]
```js
const morganLogger      = require("morgan");
const fs                = require("fs");
const rfs               = require("rotating-file-stream");
const path              = require("path");

var uuid=require('node-uuid');
var config = require('../config');


const pad = num => (num > 9 ? "" : "0") + num;
    const generator = (time, index) => {
      if (!time) return "user.log";
     
      var month =  pad(time.getMonth() + 1);
      var year=pad(time.getFullYear());
      var day = pad(time.getDate());
      var hour = pad(time.getHours());
      var minute = pad(time.getMinutes());
     
      return `${year}-${month}-${day}-${index}-user.log`;
    };
    const generator1 = (time, index) => {
        if (!time) return "errors.log";
       
        var month =  pad(time.getMonth() + 1);
        var year=pad(time.getFullYear());
        var day = pad(time.getDate());
        var hour = pad(time.getHours());
        var minute = pad(time.getMinutes());
       
        return `${year}-${month}-${day}-${index}-errors.log`;
      };
class loggers{

    constructor(){}
    log="";
     logger(logFormat){
        
        console.log("@@@@@@@",logFormat);
        this.log=logFormat;
        morganLogger.token('id', function getId (req) {
            req.id=uuid.v4();
            return req.id  
        })
        return [
            // Log all requests
            morganLogger(
                this.log,{
                   
                    skip: (req, res) => {
                        return res.statusCode > 200
                    },
                        stream: rfs.createStream(generator, {
                        interval: config.log.interval, // rotate daily
                        path: path.join(config.log.dirname,'userlogs'),
                        size: config.log.size
                      }) 
                }
            ),

            // Log error responses (4xx and 5xx)
            morganLogger(
                this.log,
                {
                   
                    skip: (req, res) => {
                        return res.statusCode < 400
                    },
                    stream: rfs.createStream(generator1, {
                        interval: config.log.interval, // rotate daily
                        path: path.join(config.log.dirname,'userlogs'),
                        size: config.log.size
                      }) 
                }
            )
        ]; 

    
}
}

const loggerss=new loggers();
module.exports={
    logger:loggerss.logger.bind(loggerss)
}
    
```

**Comment by ryhinchey** [comment]
To create a token, you call `morganLogger.token` which you're doing. Here are the docs https://github.com/expressjs/morgan#tokens.

Is there a bug or specific issue you're having?

**Comment by 8801883270** [comment]
//Here i am importing the package 
const logFormat = require('../middlewares/logger') 
//this is nothing but logformat which i am sending to middleware logger.js as parameter
const log_Format=`${"Signin"}:signin ${"requestid: "}:id ${"requestmethod: "}:method ${"requesturl: "}:url  
${"responsetime: "}:response-time ${"responsedate: "}:date ${"responsestatus"}:status`;
     //Here i am sending var logformat as parameter
      logFormat.logger(log_Format)
After this i think it should go to logger.js and get inserted in logger function and then it should get inserted into a log file which is there in my local system.
But,Its getting inserted in to logfile.
Could you please help me with this?!

**Comment by 8801883270** [comment]
*Here i am importing logger.js file********

**Comment by ryhinchey** [comment]
> After this i think it should go to logger.js and get inserted in logger function and then it should get inserted into a log file which is there in my local system.
> But,Its getting inserted in to logfile.

Do you mean it's _not_ getting inserted in to logfile?  

from the looks of it, `logFormat.logger` returns an array of morgan logger middleware functions.  I'd expect you to do something like this (if you're using express) in order to call those functions on every request:

```js
const express = require('express')
const app = express()
const logFormat = require('../middlewares/logger')

(not sure what's going on with this string here)
const log_Format=${"Signin"}:signin ${"requestid: "}:id ${"requestmethod: "}:method ${"requesturl: "}:url ${"responsetime: "}:response-time ${"responsedate: "}:date ${"responsestatus"}:status;

const logMiddleware = logFormat.logger(log_Format)

logMiddleware.forEach(middleware => {
  app.use(middleware)
}
```

**Comment by 8801883270** [comment]
//THIS IS APP.JS FILE
var http=require('http');
const express=require('express');
const app=express();
const server=http.createServer(app);
const morgan=require('morgan');
app.use((req,res,next)=>
{
  res.header('Access-Control-Allow-Origin','*');
  res.header('Access-Control-Allow-Headers','Origin,X-Requested-With,Content-Type,Accept,Authorization')
if(req.method==='OPTIONS')
{
  res.header('Access-Control-Allow-Methods','PUT,POST,PATCH,DELETE,GET');
  return res.status(200).json({});
}
next();
});
// function details(req,res,next)


app.use('/products',productroutes);

  
    server.listen(2020);
    
 
  

  app.use((req,res,next)=>
{
  const error=new Error('not found');
  error.status=400;
  next(error);
})
app.use((error,req,res,next)=>
{
res.status(error.status || 500);
// winstonlogger.log('error',error.message);
res.json({
  error:{
    message:error.message
  }
})
});

**Comment by 8801883270** [comment]
//FROM APP.JS IT WILL COME TO THIS  ROUTE.JS FILE
const ProductController=require('../controller/productscontroller');
const express=require('express')
const router=express.Router();
router.get('/',ProductController.get_all_products);

module.exports=router;

**Comment by 8801883270** [comment]
//FROM ROUTE.JS IT WILL COME TO PRODUCT CONTROLLER.JS(means on this page)
const Product=require('../models/prod');
const mongoose=require('mongoose');
const morgan=require('morgan');
const Loggers=require('../logger');
var dirname='E:/nodejs/node-rest-shop/logsfile/';
const express = require('express')
const rfs= require("rotating-file-stream");
const path= require("path");
const router=express.Router()
exports.get_all_products=(req,res,next)=>
{
    //winstonlogger.log('info',req.method);
    
    Product.find().select('name price _id productImage').exec().then(doc=>
        {      
            const response={count:doc.length,products:doc.map(singledoc=>
                {
                    return {
                    name:singledoc.name,
                    price:singledoc.price,
                    productImage:singledoc.productImage,
                    _id:singledoc._id,
                    request:
                    {
                        type:'GET',
                        url:'http://localhost:2020/products/'+singledoc._id
                    }
                    }

                })};
            if(doc.length>=0)
            {
            res.status(200).json(
                {
                    message:'comes fromsss get request',
                    allproduct:response
                }
            
            );
            morgan.token('products',function(){
                return "tokengenerated"
            })
const logformat=` ${"products"}:products`;
const a=new Loggers();
//HERE I AM CALLING LOGGER.JS LOGGER METHOD AND PASSING LOGFORMAT AS PARAMETER
//SO THIS SHOULD GO TO LOGGER.JS LOGGER FUNCTION
a.logger(logformat)

        }  
        else
        {
            res.status(200).json("No products to show");
        }
    {
        res
    }      }).catch(err=>
            {
                console.log(err);
                res.status(500).json();
            })
    
}

**Comment by 8801883270** [comment]
const morganLogger      = require("morgan");
const fs                = require("fs");
const rfs               = require("rotating-file-stream");
const path              = require("path");
const express = require('express')
const router=express.Router();
var uuid=require('node-uuid');
var dirname='E:/nodejs/node-rest-shop/logsfile/';

class Loggers{
//FROM PRODUCTCONTROLLER IT WILL COME TO LOGGER FUNCTION
    logger(logformat)  {
        
        const pad = num => (num > 9 ? "" : "0") + num;
        const generator = (time, index) => {
          if (!time) return "user.log";
         
          var month =  pad(time.getMonth() + 1);
          var year=pad(time.getFullYear());
          var day = pad(time.getDate());
          var hour = pad(time.getHours());
          var minute = pad(time.getMinutes());
         
          return `${year}-${month}-${day}-${index}-user.log`;
        };
//HERE I AM GETTING LOGFORMAT SO I AM LOGGING IN CONSOLE.LOG
        console.log(logformat);
 
         var accessLogStream = rfs.createStream(generator, {
          interval: '1m', // rotate daily
          path: path.join(dirname,'nodelog'),
          size: '10M'
         })    
               //HERE I AM PASSING LOGFORMAT AND ACCESS STREAM
//AS PER DOCUMENTATION IT SHOULD CREATE FILE IN MY LOCALSYSTEM WITH LOGFORMAT
//AND FILE IS CREATING SUCCESSFULLY BUT BLANK FILE
//HERE I WANT products: tokengenerated get inserted in my file as i created custom token in productcontroller.js and passing it as paramter to this logger function
            router.use( morganLogger(logformat, { stream: accessLogStream}));
        }   
    
  }  
//COULD YOU PLEASE HELP ME WITH THIS?
//THANK YOU FOR YOUR HELP
    module.exports = Loggers;

**Comment by ryhinchey** [comment]
> //AS PER DOCUMENTATION IT SHOULD CREATE FILE IN MY LOCALSYSTEM WITH LOGFORMAT
> //AND FILE IS CREATING SUCCESSFULLY BUT BLANK FILE
> //HERE I WANT products: tokengenerated get inserted in my file as i created custom token in productcontroller.js and passing it as paramter to this logger function
>             router.use( morganLogger(logformat, { stream: accessLogStream}));
>         }   
>     
>   }  
> //COULD YOU PLEASE HELP ME WITH THIS?

to clarify, the issue here is not about generating a morgan token, but writing to a log file with morgan?

**Comment by ryhinchey** [comment]
@8801883270 I'm going to go ahead and close this.  If you're still having an issue and can provide a reproducible example, feel free to reopen!
