### ISSUE TITLE
Morgan was unable to write log for file upload

### ISSUE THREAD

**Issue by kunjee17** [expressjs/morgan#225]
Morgan works perfectly for GraphQL project we have. But whenever we are having file upload event, though generated string was correct it is unable to write log. 

Am I missing something or some setting to allow morgan to write log even when there is file upload request?

Let me know if any further details are required from my end.

**Comment by dougwilson** [comment]
Morgan writes logs by default for all requests. We would need ideally the version of Node.js, of this module, an example app that reproduces the issue and instructons for how to make the call that is not being logged.

**Comment by ryhinchey** [comment]
Hi @kunjee17 - could you please add a snippet of your code that can reproduce this issue so I can take a look and better help you?

**Comment by kunjee17** [comment]
Here is simple mutation code taking file as an argument 

```ts
export const importFile: Mutation.ImportFileResolver = async (_, args, { container }) => {
  const importFileService = container.get(ImportFileService);
  const { stream, filename } = await args.file;

  const data = await importFileService.processData(
    Id,
    stream,
    filename
  );

  const result = {
    ...
  };

  return result;
};
```

And here how  we are using Morgan. It is default settings only. 

```ts
export const logger = morgan((tokens, req, res) => {
  const isGraphql =
    req.baseUrl && req.baseUrl.includes("graphql") && req.body && req.body.operationName;

  if (!isGraphql) {
    return [
      tokens.method(req, res),
      tokens.url(req, res),
      tokens.status(req, res),
      tokens.res(req, res, "content-length"),
      "-",
      tokens["response-time"](req, res),
      "ms"
    ].join(" ");
  }

  const { operationName, variables = {} } = req.body;

  return `GQL: ${operationName} (${Object.keys(variables)
    .map(key => `${key}: ${variables[key] && variables[key].toString()}`)
    .join(", ")}) - ${tokens["response-time"](req, res)} ms`;
});

```

So, here we are doing nothing new. And it is indeed working for all the GQL queries other than file upload one. Even  `GQL: ${operationName} (${Object.keys(variables)
    .map(key => `${key}: ${variables[key] && variables[key].toString()}`)
    .join(", ")}) - ${tokens["response-time"](req, res)} ms` is created text with [object object] for file upload as well. But was unable to insert to body part of log.

**Comment by ryhinchey** [comment]
Thanks @kunjee17!  Here's a minimal example of your logger method working with a file upload (via `multer`).  You can toggle `isGraphql` to see the different log formats.

Morgan will create a log for every request - it doesn't care if it's a file upload or not.  

What version of node are you running and what shape does `operationName` and `variables` have?  I suspect something is going wrong there if you're seeing a lot `[object object]`


```js
const express = require('express');
const multer = require('multer');
const morgan = require('morgan');


const logger = morgan((tokens, req, res) => {
  const isGraphql = true;
  //const isGraphql = false;

  if (!isGraphql) {
    return [
      tokens.method(req, res),
      tokens.url(req, res),
      tokens.status(req, res),
      tokens.res(req, res, "content-length"),
      "-",
      tokens["response-time"](req, res),
      "ms"
    ].join(" ");
  }

  const operationName = 'operation';
  const variables = {};

  return `GQL: ${operationName} (${Object.keys(variables)
    .map(key => `${key}: ${variables[key] && variables[key].toString()}`)
    .join(", ")}) - ${tokens["response-time"](req, res)} ms`;
});

const upload = multer({ dest: 'files/' });

const app = express();

app.use(logger);

app.get('*', (req, res, next) => {
  res.contentType('html');

  res.send(`
    <form action="file" method="post">
      Select image to upload:
      <input type="file" name="file">
      <input type="submit" value="Upload Image" name="submit">
    </form>
  `)
})

app.post('/file', upload.single('file'), (req, res, next) => {
  res.send(req.file);
});

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => console.log(`App is listening on port ${PORT}`));
```

**Comment by kunjee17** [comment]
Hi, here is the text that is getting generated 
`GQL: Editor_ImportFile (consultantId: null, file: [object Promise]) - 12380.561 ms`

And operation name is string. Below is shape of variables

```
{
  "Id": null,
  "file": {} // Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: {...fileObject} }
}
```

**Comment by ryhinchey** [comment]
> Hi, here is the text that is getting generated
> `GQL: Editor_ImportFile (consultantId: null, file: [object Promise]) - 12380.561 ms`

To clarify, the issue you're having is the `file: [object Promise]` part of the log?  If `file` is a Promise, calling `toString` on it will give you the string `'[object Promise]'`.

**Comment by kunjee17** [comment]
@ryhinchey yes. You can say so.

What should be done as part of logging in case of file upload? We cause we are indeed doing toString on variables.

**Comment by ryhinchey** [comment]
> What should be done as part of logging in case of file upload?

if you're trying to log the filename, you'll need to add that to your variables object or better yet, if the filename is in your request data, set a morgan token for it

**Comment by kunjee17** [comment]
@ryhinchey I did try some dumb stuff. I removed `file` property from `variables` just to check if things are working or not. But sadly they are not. Any other way to debug them. 

I have to added this piece of code 

```
if (variables?.file) {
    // remove file promise from variables
    delete variables.file;
  }

 return `GQL: ${operationName} (${Object.keys(variables)
    .map(key => `${key}: ${variables[key] && variables[key].toString()}`)
    .join(", ")}) - ${tokens["response-time"](req, res)} ms`;
```

**Comment by ryhinchey** [comment]
> just to check if things are working or not. But sadly they are not.

can you please tell me:

1. the output you're getting with the above code
2. what the `variables` object looks like
3. what you're expecting the above output to produce?

**Comment by kunjee17** [comment]
1. Output I m getting in text in return statement
```
GQL: Import_FileImport (checkForDuplicates: false, Lookup: false) - 13067.344 ms
```
1. Output I m getting in mongodb
```json
{"_id":{"$oid":"5e6a03d86630e652d0c46154"},"email":"kunjan.dalal@company.ce","method":"POST","endpoint":"/graphql","body":{},"accessed_at":{"$date":{"$numberLong":"1584006104325"}}}
```
2. Variables object
```
// file is removed from variables 
{
  "checkForDuplicates": false,
  "Lookup": false
}
```
3. expected output
It should have `body` when written in mongodb. Which is working for normal methods other than file upload. 
```json
{"_id":{"$oid":"5e6a024981a911163112a028"},"email":"kunjan.dalal@company.ce","method":"POST","endpoint":"/graphql","body":{"operationName":"GetMyProfile","variables":{"initial":true},"query":"query GetMyProfile($initial: Boolean) {\n  me(initial: $initial) {\n    ...MyProfile\n    __typename\n  }\n}\n\nfragment MyProfile on Me {\n  _id\n  AvatarPic\n  ... },"accessed_at":{"$date":{"$numberLong":"1584005705756"}}}
```

**Comment by ryhinchey** [comment]
@kunjee17 I'm having a difficult time following your code samples.  Could you create a sample repo with a minimal reproducible example?  Given the variables object and output you've provided above, the log looks correct.  



> 1. expected output
>    It should have `body` when written in mongodb. Which is working for normal methods other than file upload.
> 
> ```json
> {"_id":{"$oid":"5e6a024981a911163112a028"},"email":"kunjan.dalal@company.ce","method":"POST","endpoint":"/graphql","body":{"operationName":"GetMyProfile","variables":{"initial":true},"query":"query GetMyProfile($initial: Boolean) {\n  me(initial: $initial) {\n    ...MyProfile\n    __typename\n  }\n}\n\nfragment MyProfile on Me {\n  _id\n  AvatarPic\n  ... },"accessed
> ```

I'm not following this.  Adding a minimal reproducible example will help!

**Comment by kunjee17** [comment]
@ryhinchey give me some time. I ll add a minimum repo project for same.

**Comment by kunjee17** [comment]
@ryhinchey I m closing this issue for now. We have another logging attached with graphQL that is picking it up client queries. I ll come to this little bit later. And will re open it with example project. 

Hope that is OK.
