### ISSUE TITLE
Add 'save to mongodb' feature or add more details about it in the README.md

### ISSUE THREAD

**Issue by MJB-Khorasani** [expressjs/morgan#246]
Hi, I wanna save my logs to the database (MongoDB) but I don't wanna use morgan-mongodb or other packages. is there any way for me to do that by myself? something like this: save logs into a collection as a document before logging.

**Comment by dougwilson** [comment]
Thanks for your request! Unfortunately I am not familiar with mongodb in that way, so would not be able to add any such information. You're welcome to contribute it as a pull request, though!
