### ISSUE TITLE
Getting vulnerable issue morgan@1.10.0

### ISSUE THREAD

**Issue by YashvantYadavTR** [expressjs/morgan#278]
Please check below
Using morgan@1.10.0
-- morgan@1.10.0
 `-- debug@2.6.9 deduped

1 high severity vulnerabilities

how to resolve above issue?

**Comment by dougwilson** [comment]
Hi 👋 and sorry you are having an issue. Unfortunately I'm not sure off-hand what issue you are getting. Please go ahead and follow our process to report security issues outlined at https://github.com/expressjs/express/blob/master/Security.md and provide as much information as poasible so we can assess.
