### ISSUE TITLE
Expose `stream.write` as option

### ISSUE THREAD

**Issue by agnjunio** [expressjs/morgan#279]
I love what Morgan does, but I only have the need to customize this line:

```
stream.write(line + '\n')
```

I want to be able to pass custom req.properties as metadata to my logger, so in my use-case I would need morgan to call:
```
stream.write(line, ...customStuffThatDependsOnUpdatedRes)
```

Is there a way I can do that?

**Comment by agnjunio** [comment]
Noticed that this is addressed by https://github.com/expressjs/morgan/pull/272

**Comment by dougwilson** [comment]
Hi @agnjunio there isn't, but `.write` method cannot accept just random extra parameters, it seems. This is the method signature: https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback

> writable.write(chunk[, encoding][, callback])
