### ISSUE TITLE
Feature request: log both before & after the request

### ISSUE THREAD

**Issue by thomas-riccardi** [expressjs/morgan#40]
The usual request loggers log after the request was responded, because at this point we have all the data: response time, return code, etc... This is what `morgan` does by default.

But for debug purpose it's often useful to have a log entry when the request was just received, `morgan` also provides this feature with the `immediate` flag.

However, what we really need when debugging it immediate log _and_ all the response information. The only way to implement this is to log two times: one like immediate, and one like the default. 
We then need something to correlate both logs (a correlation id: a counter, or some other thing).
And finally: something to distinguish between both logs entries (a visual clue like a prefix).

Without this feature the `immediate` feature is usually useless. Or am I missing a standard use-case?

**Comment by james-gardner** [comment]
What if you're using CLS for storing the correlation id? Do we just call .token and ignore the req res parameters?

**Comment by johncmunson** [comment]
@dougwilson in reference to your proposed solution for a correlation id above... what about when you are logging from layers that are separate from express routing, such as service or repository layers? Will the `req` object need to be explicitly passed around from layer to layer? In addition... would a separate logging solution be needed in these places, since `morgan` seems to only function as middleware?

**Comment by dougwilson** [comment]
Hi @johncmunson my response was to answer the OP's specific use-case and question, and OP closed the issue as it works for them. If you have a different/additional questions, please open a new issue so everyone in this repo will see it and can jump in to help, as well as not drag back in the original reporters from years ago (they are getting emails for all our responses here). You can always link back to an issue (like this one) if it's content is relevant to your question.
