### ISSUE TITLE
how to add colors for custom log tokens

### ISSUE THREAD

**Issue by mderazon** [expressjs/morgan#49]
Hi there,

I couldn't find any example on how to define colors to custom log tokens.
Is there a snippet somewhere I can use ?

Thanks

**Comment by dougwilson** [comment]
Sadly, it's not a feature of a string format, only if you define the format as a function :(
```js
app.use(morgan(function (tokens, req, res) {
  return chalk.blue(tokens.method(req, res))
    + ' ' + chalk.green(tokens.url(req, res))
    + ' ' + chalk.red(tokens['response-time'](req, res))
}))
```

**Comment by mderazon** [comment]
That will do, thanks :+1:

**Comment by dougwilson** [comment]
No problem :)
