### ISSUE TITLE
add text next to a token without needing a space

### ISSUE THREAD

**Issue by bchr02** [expressjs/morgan#50]
It would be cool if there was a way to add text next to a token without needing a space or needing to figure out how to rewrite the token so that it includes the text.

For ex:
````javascript
app.use(logger(':method :status :url :response-time ms :res[content-length]'));
````
What if I want to remove the space between the ms and the :repsonse-time without rewritting the token? Is there a way to do this? Thanks.

**Comment by dougwilson** [comment]
Not with the string syntax, but you can do this if you use a custom function for the formatting:
```js
var morgan = require('morgan')

app.use(morgan(function (tokens, req, res) {
  return tokens.method(req, res)
    + ' ' + tokens.status(req, res)
    + ' ' + tokens.url(req, res)
    + ' ' + tokens['response-time'](req, res) + 'ms'
    + ' ' + tokens['content-length'](req, res)
}))
```

**Comment by bchr02** [comment]
That works! Thank you.

**Comment by denisu** [comment]
```
app.use(logger(':method :status :url :response-time\\ms :res[content-length]'));
```
works too

**Comment by dougwilson** [comment]
@denisu that only works because `'\m'` is not an escape in JavaScript. If, perhaps, he wanted the end to me "ns" (with an n instead of m), then your solution wouldn't work, since `'\n'` would translate to a newline character.

**Comment by denisu** [comment]
You are right, its a little hacky, you could also squeeze a valid escape character in there, but it might produce dirty logfiles.
```
app.use(logger(':method :status :url :response-time\0ms :res[content-length]'));
app.use(logger(':method :status :url :response-time\bms :res[content-length]'));
```
