### ISSUE TITLE
How to log writing file AND showing in console

### ISSUE THREAD

**Issue by jinwyp** [expressjs/morgan#51]
http://stackoverflow.com/questions/27230365/morgan-logger-express-js-writing-file-and-showing-in-console 

I can't find the way to do that from morgan readme ?

**Comment by dougwilson** [comment]
Simply `app.use` two copies of `morgan`:
```js
var logger = require('morgan')

app.use(logger('common', {stream: fs.createWriteStream('./access.log', {flags: 'a'})}))
app.use(logger('dev'))

```
