### ISSUE TITLE
Syslog

### ISSUE THREAD

**Issue by thedug** [expressjs/morgan#52]
Is it possible to config morgan to write to syslog via udp?

**Comment by dougwilson** [comment]
I'm sure it is. Is there a particular Node.js module you are going to use to write to syslog? If you can point me there, I can see if I can craft you an example. Otherwise the basic example is

1. Create yourself a custom `WriteStream` that writes the output to where you need.
2. Provide that write stream to morgan as the [stream option](https://github.com/expressjs/morgan#stream)

**Comment by thedug** [comment]
This is an example of a simple syslog logger. It's opening a connect and then writing to the socket. https://github.com/cloudhead/node-syslog/blob/master/lib/node-syslog.js

**Comment by dougwilson** [comment]
This is the basics for wrapping that module as a standard Node.js WritableStream. As a disclaimer, I haven't tested it, mainly because I'm on Windows and don't have a syslog to point at, but hopefully it helps point in the right directions.

```js
var express = require('express') // npm i express
var morgan = require('morgan') // npm i morgan
var stream = require('stream') // http://nodejs.org/api/stream.html
var syslog = require('syslog') // npm i syslog
var util = require('util')

app.use(morgan('combined', {stream: new SyslogStream()}))

function SyslogStream() {
  stream.Writable.call(this, { decodeStrings: false })
  this.logger = syslog.createClient(514, 'localhost')
}

util.inherits(SyslogStream, stream.Writable)

SyslogStream.prototype._write = function _write(chunk, encoding, callback) {
  this.logger.info(chunk)
  callback()
}
```

**Comment by brenc** [comment]
This is a bit easier with modern-syslog (just leaving this here for anyone else who finds this, like I did):

```javascript
syslog.open('process name', syslog.option.LOG_CONS | syslog.option.LOG_PID,
                    syslog.facility.LOG_LOCAL4);

app.use(morgan('combined', {
    stream: new syslog.Stream(syslog.level.LOG_INFO, syslog.facility.LOG_LOCAL4),
}));
````

**Comment by obiwan96** [comment]
Hi,

While I try this code, I get these error messages.
Is there any required specific version of packages?
Can you fix this problem? 
Thank You!



```
node:internal/streams/writable:291
      encoding = state.defaultEncoding;
                       ^

TypeError: Cannot read properties of undefined (reading 'defaultEncoding')
    at _write (node:internal/streams/writable:291:24)
    at SyslogStream.Writable.write (node:internal/streams/writable:334:10)
    at Array.logRequest (/home/ubuntu/vaspbackend/node_modules/morgan/index.js:130:14)
    at listener (/home/ubuntu/vaspbackend/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/ubuntu/vaspbackend/node_modules/on-finished/index.js:100:5)
    at callback (/home/ubuntu/vaspbackend/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/home/ubuntu/vaspbackend/node_modules/ee-first/index.js:93:5)
    at ServerResponse.emit (node:events:402:35)
    at onFinish (node:_http_outgoing:830:10)
    at afterWrite (node:internal/streams/writable:497:5)
```


> This is the basics for wrapping that module as a standard Node.js WritableStream. As a disclaimer, I haven't tested it, mainly because I'm on Windows and don't have a syslog to point at, but hopefully it helps point in the right directions.
> 
> ```js
> var express = require('express') // npm i express
> var morgan = require('morgan') // npm i morgan
> var stream = require('stream') // http://nodejs.org/api/stream.html
> var syslog = require('syslog') // npm i syslog
> var util = require('util')
> 
> app.use(morgan('combined', {stream: new SyslogStream()}))
> 
> function SyslogStream() {
>   stream.Writable.call(this, { decodeStrings: false })
>   this.logger = syslog.createClient(514, 'localhost')
> }
> 
> util.inherits(SyslogStream, stream.Writable)
> 
> SyslogStream.prototype._write = function _write(chunk, encoding, callback) {
>   this.logger.info(chunk)
>   callback()
> }
> ```
