### ISSUE TITLE
io.js compatibility

### ISSUE THREAD

**Issue by sabrehagen** [expressjs/morgan#54]
When using morgan in its most basic format i.e. `app.use(morgan({ format: 'dev' }));` in io.js 1.3.0, there is no console output. Sorry I can't provide any more info!

**Comment by dougwilson** [comment]
Ok, let me know if you have any more information. io.js doesn't work well on Windows, so I cannot try it out myself, so will need to hear back from someone to take any action on this. It's always possible there is a bug in io.js, of course. Officially this module _only_ supports Node.js 0.8, 0.10, and 0.12, but if there is a simple fix of io.js stuff, just let me know.

**Comment by dougwilson** [comment]
@sabrehagen can you clone this repo and run the test suite in io.js at least and paste me the output?

**Comment by sabrehagen** [comment]
@dougwilson well, all seems smooth:

> morgan@1.5.1 test morgan-master
> mocha --check-leaks --reporter spec --bail



  morgan()
    arguments
      √ should use default format
      format
        √ should accept format as format name
        √ should accept format as format string
        √ should accept format as function
        √ should reject format as bool
        back-compat
          √ should accept options object
          √ should accept format in options for back-compat
          √ should accept format function in options for back-compat
    tokens
      :date
        √ should get current date in "web" format by default
        √ should get current date in "clf" format
        √ should get current date in "iso" format
        √ should get current date in "web" format
        √ should be blank for unknown format
      :req
        √ should get request properties
      :res
        √ should get response properties
      :remote-addr
        √ should get remote address
        √ should use req.ip if there
        √ should work on https server
        √ should work when connection: close
        √ should work when connection: keep-alive
        √ should work when req.ip is a getter
        √ should not fail if req.connection missing
      :remote-user
        √ should be empty if none present
        √ should support Basic authorization
        √ should be empty for empty Basic authorization user
      :response-time
        √ should be in milliseconds
        √ should be empty without hidden property
        √ should be empty before response
      :status
        √ should get response status
        √ should not exist before response sent
        √ should not exist for aborted request
    formats
      combined
        √ should match expectations
      common
        √ should match expectations
      default
        √ should match expectations
      dev
        √ should color 200 green
        √ should color 500 red
        √ should color 400 yelow
        √ should color 300 cyan
      short
        √ should match expectations
      tiny
        √ should match expectations
    with buffer option
      √ should flush log periodically (1001ms)
      √ should accept custom interval (202ms)
    with immediate option
      √ should log before response
    with skip option
      √ should be able to skip based on request
      √ should be able to skip based on response


  45 passing (1s)

**Comment by dougwilson** [comment]
Ok. Can you install the latest `morgan`, copy the following into a file and run it and paste the output?
```js
var http = require('http')
var morgan = require('morgan')

var log = morgan('dev')

var server = http.createServer(function (req, res) {
  log(req, res, function () {
    res.setHeader('Content-Type', 'text/plain')
    res.setHeader('Content-Length', '6')
    res.end('hello!')
  })
})

server.listen(function () {
  var url = 'http://127.0.0.1:' + this.address().port + '/'
  http.get(url, function (res) {
    res.resume()
    server.close()
  })
})
```

**Comment by sabrehagen** [comment]
actually, i'm sorry to have troubled you, this is only happening when launching with nodemon. when running only with node/iojs this works fine. you can delete the issue!

**Comment by dougwilson** [comment]
Ah. https://github.com/remy/nodemon/issues/468#issuecomment-70563238 sounds like your issue. Have you tried updating `nodemon` to at least 1.3.1?

**Comment by sabrehagen** [comment]
Yep, that was what was needed. It's frustrating when your packages are out of date and you have no idea why things aren't functioning! Thanks for the help.
