### ISSUE TITLE
Ignore socket.io poll

### ISSUE THREAD

**Issue by sean-hill** [expressjs/morgan#57]
Hey there awesome dudes,

I LOVE THIS LIBRARY.

I just implemented socket.io on my server, and now I see this log all the stinking time:

    Wed, 15 Apr 2015 15:27:14 GMT - GET /socket.io/?EIO=3&transport=polling&t=1429111634816-32&b64=1 responded 404 in 0.177 ms

Is there a way to ignore logs with a url that contains `/socket.io`? Thanks!

**Comment by sean-hill** [comment]
Got it.

`skip: function(req, res) { return req.url.indexOf('/socket.io') !== -1 }`

**Comment by dougwilson** [comment]
Yep, using the `skip` option certainly works :) Another way is to just `use` this middleware _after_ the middleware that is responding to those socket.io URLs, as only requests that travel through the middleware will actually get logged.

Edit: I realized that URL is getting a 404, so I guess you can't do that :)
