### ISSUE TITLE
Ordering of log lines

### ISSUE THREAD

**Issue by sabrehagen** [expressjs/morgan#58]
Often the log lines get out of order, or one request will be fully coloured green like the 200 request colour. I'm guessing this is due to the async nature of the console, just alerting you to it.
![2015_04_20_11_02_28_c_windows_system32_cmd exe_server_remote bat_](https://cloud.githubusercontent.com/assets/1094600/7222331/4a66a32a-e74f-11e4-8f63-306e72f791eb.png)

**Comment by dougwilson** [comment]
Are you having multiple `morgan` instances write to the same console?

**Comment by dougwilson** [comment]
In the end, all we do is call `process.stdout.write(line + '\n')` for each line. If they are getting mixed lines, you either have multiple `morgan`s writing to the same console (perhaps using `cluster`?) and the shell you are using is getting confused or Node.js itself has some kind of bug.

**Comment by sabrehagen** [comment]
Yes, clustering must be the issue. Thanks for that.
