### ISSUE TITLE
Response time in seconds?

### ISSUE THREAD

**Issue by prashantbaid** [expressjs/morgan#59]
Is there a way to change the response time from milliseconds to seconds ?

**Comment by dougwilson** [comment]
You would just need to add your own token (from https://github.com/expressjs/morgan#use-custom-token-formats):
```js
morgan.token('response-time-seconds', function getResponseTimeInSeconds(req, res) {
  return Math.ceil(this['response-time'](req, res) / 1000)
})
```

And then use `:response-time-seconds` in your format string. Since tokens can take arguments, I'm going to add an argument to the `:response-time` token to choose the units.

**Comment by prashantbaid** [comment]
Sorry for the late reply. Thanks, this worked like a charm :)
