### ISSUE TITLE
How do I log output to file?

### ISSUE THREAD

**Issue by Findiglay** [expressjs/morgan#68]
Hi, I was hoping you could help me out here.

I'm trying to log requests to a file. I'm using:
```js
app.use(morgan('dev'));
app.use(morgan('common', {stream: fs.createWriteStream('./access.log', {flags: 'a'})}));
```
This creates a file called access.log in the root directory, I also have a 'common' flag in my console before each logged request. But, the file access.log remains empty. Is there anything I'm doing wrong here?

**Comment by dougwilson** [comment]
Hm, that seems to work for me just fine. I would try two things:

1. Provide an absolute path for the `fs.createWriteStream` to be sure it is using the same file you are expecting.
2. Can you provide a full app that reproduces the issue? It could be caused by something you have in your app not displayed above, maybe?

**Comment by Findiglay** [comment]
Hi Doug, thanks for the reply.

I've changed to absolute path (I think), but still no diff. I'm using fullstack-angular-generator as a base. Morgan already comes with, and is set in this file:

https://github.com/Findiglay/vetstodo/blob/master/server/config/express.js

The log is being created here, but remains empty: https://github.com/Findiglay/vetstodo/blob/master/access.log

Although as mentioned I see the 'common' flags in my console.

Cheers,

**Comment by dougwilson** [comment]
@Findiglay any reason why the repository has `{flags: 'w'}` instead of `{flags: 'a'}`?

**Comment by Findiglay** [comment]
@dougwilson that flag should be valid if the file has already been created I understand,

see https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

I can confirm this is a Windows 8 issue, the same code is working fine on iOS. I'm happy to close this as it may be an irregular issue.

**Comment by dougwilson** [comment]
Gotcha. I run Windows 7 and it writes to the file just fine as well, which is why I was asking. I'm also using Node.js 0.10.x if that helps, as I don't know which version of Node.js you're using (because, perhaps it's a Node.js bug?).
