### ISSUE TITLE
Export compile function to be used by others

### ISSUE THREAD

**Issue by varemenos** [expressjs/morgan#69]
Could you please export the compile function so we can define custom and colored formats like the `dev` one.

for example:
```js
morgan.format('myformat', function(tokens, req, res){
  var color = 32; // green
  var status = res.statusCode;

  if (status >= 500) color = 31; // red
  else if (status >= 400) color = 33; // yellow
  else if (status >= 300) color = 36; // cyan

  var fn = morgan.compile('\x1b[0m:method :url \x1b[' + color + 'm:status \x1b[0m');

  return fn(tokens, req, res);
});

app.use(morgan('myformat'));
```

Currently that's not possible because `compile` is private

**Comment by margaritis** [comment]
:+1:

**Comment by dougwilson** [comment]
I can do this; it'll take a little bit, because making it public means it has to be fully tested independently :)

**Comment by margaritis** [comment]
Sounds great @dougwilson !

**Comment by dougwilson** [comment]
Once 1.6.0 is published, then you're OP example will function just fine :)

**Comment by varemenos** [comment]
Thanks a lot @dougwilson

**Comment by margaritis** [comment]
Thank you @dougwilson!
