### ISSUE TITLE
Option to skip new line when writing to stream

### ISSUE THREAD

**Issue by zam6ak** [expressjs/morgan#70]
Hi

Is there a way to set up morgan to skip adding new line when using stream option?
I am combining morgan's output to winston and both are adding LF line feed which results in double new lines...I can strip out the newline when it comes from morgan but it would be faster if it wasn't there at all in this scenario...

Thoughts?
Amir

**Comment by dougwilson** [comment]
We don't even guarantee that a call to `.write` will be a single line. To me, it sounds like you are assuming that only a single line will ever come to `.write` and are passing in a function there instead of giving a real stream to the `stream` option :)

It is best if you use something like the `split` module like our tests do:

```js
var morgan = require('morgan')
var split = require('split')

winstonStream = split().on('data', function (line) {
  winstonLogger.log(line)
})

app.use(morgan({ stream: winstonStream }))
```

**Comment by zam6ak** [comment]
It's fine if call to write is multi line. I was just looking for a way to remove last newline added by morgan.
And yes, I am using a function instead of the real stream in order to integrate the two. (according to this article: http://tostring.it/2014/06/23/advanced-logging-with-nodejs/) 

I will take a look at the split module.

Thanks

**Comment by dougwilson** [comment]
The `split` module removes the new line, so in the example above, the `line` variable does not have the trailing new line.

**Comment by dougwilson** [comment]
If I were to fix that article, I would change the first code snippet to be the following to work:
```js
var split = require('split');
var winston = require('winston');
winston.emitErrs = true;

var logger = new winston.Logger({
    transports: [
        new winston.transports.File({
            level: 'info',
            filename: './logs/all-logs.log',
            handleExceptions: true,
            json: true,
            maxsize: 5242880, //5MB
            maxFiles: 5,
            colorize: false
        }),
        new winston.transports.Console({
            level: 'debug',
            handleExceptions: true,
            json: false,
            colorize: true
        })
    ],
    exitOnError: false
});

module.exports = logger;
module.exports.stream = split().on('data', function (message) {
  logger.info(message);
});
```

**Comment by zam6ak** [comment]
Do you think this would cause any performance issues in heavily used apps?
It does work!

Again thanks a lot!

**Comment by dougwilson** [comment]
I would be pretty surprise if it did :)

**Comment by dougwilson** [comment]
In the end, of course, you do have to trade some for "it working correctly" vs "it seems to work so far". If you wanted to continue using just a function for `write`, you can always simply chop off the last character, as it wouldn't introduce any more risk.

**Comment by zam6ak** [comment]
What kind of 'browse-able activity' would cause morgan to output multiline to stream?
:)

**Comment by JimmyTournemaine** [comment]
The discussion is old but still relevant in my opinion cause this is the top 1 of my google research and I still have this trouble in 2021.
So, I share for all intents and purposes the simple solution I made without the need to install any third-party dependency:
```typescript
app.use(morgan('combined', {
  stream: new Transform({
    transform: (chunk: string|Buffer, encoding, callback) => {
      chunk.toString().split('\n').filter((v) => v).forEach((v) => logger.http(v));
      callback();
    }
  })
}));
```

**Comment by PathToLife** [comment]
Here's the culprit, tagged below

https://github.com/expressjs/morgan/blob/master/index.js#L130

May I ask if maintainers would like me to work on PR that adds an option to morgan that can disable the above?

Till then I'm doing (typescript)

```
const stream: StreamOptions = {
    write: (msg: string) => logger.http(msg.trim()),
}

export const morganLogger = morgan(
    ':method :url :status :res[content-length] - :response-time ms',
    {
        stream,
        skip: () => false,
    }
)
```

**Comment by dougwilson** [comment]
For those who have been posting on this issue from 6 years ago, please open new issues, as no one but the participants of the original issue will likely see your issue report or comments.
