### ISSUE TITLE
Any existing patterns to store logs in a db?

### ISSUE THREAD

**Issue by pajtai** [expressjs/morgan#71]
Specifically I'd like to use morgan to write documents to a mongo db.

**Comment by dougwilson** [comment]
I'm not very familiar with MongoDB, but I found this code example in an old issue here which may help you: https://github.com/expressjs/morgan/pull/44#issuecomment-62309400

Otherwise, you may need to just ask on like Stackoverflow.com or something :)

**Comment by pajtai** [comment]
thanks!

**Comment by serganus** [comment]
@pajtai In case you want to log more for every request, check this [mongo-morgan-ext](https://www.npmjs.com/package/mongo-morgan-ext)
