### ISSUE TITLE
Response time should be a number, not a string

### ISSUE THREAD

**Issue by palmerabollo** [expressjs/morgan#74]
The token ["response-time" is converted to a string](https://github.com/expressjs/morgan/blob/master/index.js#L239). IMO the behavior should be consistent with other numeric tokens such as "status", that is a number.

To put it in context, I write logs as JSON, so the format is important and makes it much easier to further process logs (for example, calculate the average response time).

The change is easy using ```parseFloat```. If this sounds good, I can send a PR.

**Comment by dougwilson** [comment]
Our interface is only strings. Returning a number causes our formatting to replace a `0` with a `-`; the issue here is actually that we are not stringifying the status code, rather than the other way around. I would accept a PR to stringify the status code, though :)

**Comment by palmerabollo** [comment]
Thanks for the quick answer, @dougwilson. You are right, the token 'status' was fixed in 1.6.0 (I'm still using 1.5.x). Perhaps morgan is not the best express middleware to log requests as JSON.

**Comment by dougwilson** [comment]
> Perhaps morgan is not the best express middleware to log requests as JSON.

Right, sadly it is not :( There was a sort-of start to get it going, but hasn't gotten very far. The module's roots are just access.log style line logging, so it currently doesn't git too many other use-cases :(
