### ISSUE TITLE
getip should take care of x-forwarded-for

### ISSUE THREAD

**Issue by prasad83** [expressjs/morgan#76]
```javascript

function getip(req) {
  return req.headers['x-forwarded-for'] // 1st priority
    || req.ip
    || req._remoteAddress
    || (req.connection && req.connection.remoteAddress)
    || undefined;
}

**Comment by dougwilson** [comment]
Hi! So that suggested change wouldn't work, not only because the header is a comma-separated listed, but because it's a header people can just forge it. Are you using Express? Express provides `req.ip` with x-forwarded-for support for you, which is why we try `req.ip` first.

**Comment by jdonald** [comment]
In case others come across this and end up using `morgan.token('remote-addr', ...)` like I was, the simpler solution is along the lines of what @dougwilson said above.

If behind a proxy or load balancer, tell Express to fill in req.ip with x-forwarded-for by doing:
```javascript
app.set('trust proxy', true); 
```
[1] https://expressjs.com/en/guide/behind-proxies.html

**Comment by joer14** [comment]
My apologies for commenting on an old issue but I wanted to provide alternative solution for anyone who is writing code that may be deployed across varied infrastructure (different proxies, cloud functions, etc).

There is a small but relatively popular npm module [request-ip](https://github.com/pbojinov/request-ip), that resolves the client ip address across various different setups.

```
import requestIp from 'request-ip';

morgan.token('trueIp', req => requestIp.getClientIp(req));
```

If you're not averse to yet another npm module then hopefully this helps 😄
