### ISSUE TITLE
3 digit precision on millisecond value?

### ISSUE THREAD

**Issue by sunib** [expressjs/morgan#78]
Hi!

Not a very important issue, but I'm just curious.

I just updated an server that was running a version of last year. I noticed that the `:response-time` field is now shown with a precision of 3 digits after the decimal point. Instead of no digits after the point.

Personally I find it more difficult to view logfiles, why is it shown with such a big precision at this moment?

Best regards,
Simon Koudijs

**Comment by dougwilson** [comment]
So the change happened in version 1.1.0, as part of PR #14 . Prior to the change, it was shown with 1ms resolution only accurate +/- 14ms (depending on platform). I believe the reasoning is that these days with such fast processors, 0.1ms is a measurable difference that can be corrected rather than noise.

We can probably add an option to control the number of digits, if that's of interest to you?

**Comment by Sunib** [comment]
Ok, intresting. The setting would be nice in my opinion! 

Just a thought: The default of 3 digits implies a measure precision of 1 nano second, is that really possible inside V8? I could imagine that you would have 1 digit decimal precision.

**Comment by dougwilson** [comment]
V8 will actually measure all the way down to the 8th place, at least. Here is a simple command on my machine:
```
$ node -pe 't=process.hrtime();process.hrtime(t)[1]*1e-6'
0.004251
```

This means that just on my crappy laptop, I get all the way down to the third decimal easily (the number is in ms).

**Comment by Sunib** [comment]
Ok, this is new for me. Very interesting. In the end one could still ask the question how much precision is left when the tcp/ip stack is also taken into account. But I'm not an expert on that topic.

I would really like the option to disable the digits (as it was). I guess that most people don't need the precision for debugging. But I could live without it off course.

Thank you for your information anyway.

**Comment by dougwilson** [comment]
Hi @sunib , sorry for letting this sit for so long, as the feature is trivial to implement. One thing that is interesting is that servers like Apache let you do either seconds or microseconds for the duration in the logs, which just happens to be exactly what we are doing by default (0.001 ms = 1 μs).

Are you still interested in in me implementing this change?
