### ISSUE TITLE
Logging the response object with Morgan

### ISSUE THREAD

**Issue by mayur-arora** [expressjs/morgan#79]
Is there a way we can log the entire response object using morgan , say if we have a non-200 status code ?

**Comment by dougwilson** [comment]
Hi @mayur-arora , as this is a line-based logger, there is nothing like this built-in. There is also a lot of things in a `res` object that cannot be represented when printing to the console.

If you want to use morgan for this task, one way would be to create your own token (https://github.com/expressjs/morgan#creating-new-tokens):
```js
morgan.token('dump_res_on_error', function (req, res) {
  return res.statusCode !== 200 ? JSON.stringify(res) : undefined
})
```

And then you would define your own format, using your token:
```js
app.use(morgan(':method :url :status :dump_res_on_error'))
```

**Comment by mayur-arora** [comment]
Instead of JSON.stringify I used util.inspect(res). Stringify gives me a circular JSON array . The date-time token provided by default only provides date in GMT . I had to write a custom token to get dat-time in Indian Standard Time 
morgan.token("date-time",function(req,res){
    return Date().toLocaleString();
})
