### ISSUE TITLE
Log File Getting Truncated

### ISSUE THREAD

**Issue by mayur-arora** [expressjs/morgan#81]
So I looked around for this one a lot, could not find anything. I have been able to log using morgan in a file but the file keeps getting truncated with every entry. I created a module for morgan logging:
  
```js
var morgan = require("morgan");
var util = require("util");
var morganConfig = require("config").morganConfig;
var fs = require("fs");

morgan.token("dump_res_on_err", function (req, res) {
    if (res.statusCode >= 400) {
        return util.inspect(res);
    }
    else return "{}";
});

morgan.token("date-time", function (req, res) {
    return Date().toLocaleString();
})

morgan.format("loopback-log", "Morgan :date-time :method :url :status :response-time ms :dump_res_on_err");


if (morganConfig.mode === "console") {
    module.exports.log = morgan("loopback-log");
}
else if (morganConfig.mode === "file") {
    var accessLogStream = fs.createWriteStream("/Users/mayur.arora/Desktop/morgan.log", {flags: 'a'});
    module.exports.log = morgan("loopback-log", {
        stream: accessLogStream
    });
}
```
and in my server file , just use this:
```js
app.use("/api/*",morganLogger.log);
```
It works ; the log is being written to but as I said it keeps getting truncated. Pick the file to be written to from a config 
```js
 "morganConfig":{
    "mode":"file",
    "fileName":"/var/log/a/b/c/nodeServerLogFile.log"
  }
```

**Comment by dougwilson** [comment]
Hi! In what way is the log getting truncated, exactly? For one thing, you cannot use `util.inspect`, because that will return strings with multiple lines and in morgan, which is a line-based logger, your entries can only be a single line for things to work properly.

**Comment by dougwilson** [comment]
One thing you can try is replacing `return util.inspect(res);` with `return util.inspect(res).replace(/\n/g, '');` to put that all on one line (which is required to use this module) and see if it's still getting truncated?

**Comment by mayur-arora** [comment]
'truncated' as in only the last entry remains in the log and the previous
ones are removed.
Even if I get rid of uti.inspect() :

morgan.token("dump_res_on_err",function(req,res){
    return "{}"; //just a string here
});

It still keeps on truncating the file and I get to see the last log entry only.

I am using the flag 'a' though.



On Wed, Sep 9, 2015 at 1:04 AM, Douglas Christopher Wilson <
notifications@github.com> wrote:

> One thing you can try is replacing return util.inspect(res); with return
> util.inspect(res).replace(/\n/g, ''); to put that all on one line (which
> is required to use this module) and see if it's still getting truncated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expressjs/morgan/issues/81#issuecomment-138678025>.
>



-- 
Regards
Mayur Arora

**Comment by dougwilson** [comment]
Yea, I'm not sure. I tried you exact code above and, even with just the plain `util.inspect`, all requests I make are in the file, so I'm not sure what is going on. Without a way to reproduce, unfortunately, there isn't much I can do, and besides the `util.inspect`, nothing seems off in your code.

**Comment by mayur-arora** [comment]
hey @dougwilson  so you tried this code and it worked fine  for you ?

**Comment by dougwilson** [comment]
Exactly

**Comment by dougwilson** [comment]
Of course, since your code was bot complete, and I had to fill in a lot of blanks like how is your express app created? what versions of all the modules are you using? what version of node.js? what operation system? how are you making the requests? and a lot more, it's possible that between us, anything you did not write out and I had to guess could be the issue.

**Comment by mayur-arora** [comment]
So it is working for me as well. I am using Morgan now. The documentation mentions of colored status codes if the format is 'dev'. Is there a way to get colored status codes in custom formats as well ?Documentation does not mention of this.

**Comment by dougwilson** [comment]
Hi!  Good to hear you got it working :) The `dev` format is just the only _built-in_ format that is colored. You can color any custom format you like, though, as the format specifiers are just strings. You can see a simple example using `chalk` at https://github.com/expressjs/morgan/issues/49#issuecomment-71305867

**Comment by mayur-arora** [comment]
hey @dougwilson I came across the Morgan middleware being used in the loopback documentation and decided to go for it. It serves my purpose well- logs the details I want as a middleware - at one place. Can 'morgan' be used to log the calls being made from the loopback layer to the backend systems ? I mean a place where this could be handled by 'morgan' . I would like to log the data being sent by the loopback operations ( defined in its data source file) ? This seems to be a little tricky - spent an entire day on this ; couldn't come up with anything.

**Comment by dougwilson** [comment]
Hi @mayur-arora , no, that is not in the scope of what morgan does, unfortunately. This module only does (and will only ever do) request logging for requests/responses that go in/out of your HTTP server. It does not interact with backend calls at all.
