### ISSUE TITLE
Enable logging based on file size ?

### ISSUE THREAD

**Issue by ramprakash-ravi** [expressjs/morgan#82]
Is there a option of creating the log files based on the file size ?
For example if the size of the file is set to 3MB, the logger has to happen in a new file once the file size is reached to 3MB max, as the daily basis of logging happening with the option of :frequency: 'daily'

**Comment by dougwilson** [comment]
Hi! All morgan does is log to the stream you provide it; you could do this with morgan, all you need is a stream that does the functionality you're looking for. We do provide an example of this in our log rotation example (https://github.com/expressjs/morgan#log-file-rotation), which uses the `file-stream-rotator` module on npm.

Now, that module does not support rotation based on file size, but perhaps they can add the feature, or you can find/create a stream module that does provide the functionality you're looking for :)
