### ISSUE TITLE
log file rotation not work

### ISSUE THREAD

**Issue by assgod** [expressjs/morgan#83]
I have used the example of 'log file rotation', but it could not log and save.
file-stream-rotator is the newest version

**Comment by assgod** [comment]
it saved when I close the app. But how can I log in terminal at the same time, it doesn't output in terminal when I use the file-stream-rotator

**Comment by dougwilson** [comment]
Hi! So if you would like the logs to go two places at once (a file and the terminal), all you have to do is `app.use()` two morgan instances: one to write to the file, and the other to write to the terminal. Here is a simple example:
```js
// setup the rotated file logger
app.use(morgan('combined', {stream: accessLogStream}))

// setup the terminal logger
app.use(morgan('dev'))
```
