### ISSUE TITLE
if use proxy in koa, can't show the real ip

### ISSUE THREAD

**Issue by wohugb** [expressjs/morgan#84]
change getip function in morgan module index.js, and req.headers['x-real-ip'] will show the real ip!

**Comment by dougwilson** [comment]
Hi! We simply use `req.ip` if it exists, which is does in Koa. Here is their implementation: https://github.com/koajs/koa/blob/master/lib/request.js#L363

You would have to request for Koa to either support the `X-Real-IP` header, or add a Koa middleware that replaces the `req.ip` getter to look in that header for your application.

**Comment by holymonson** [comment]
Hi! Koa supports `X-Forwarded-For` in `request.ip` instead of `req.ip`, while `req.ip` always refers to raw connection ip. Is it possible using `request.ip` in preference to `req.ip`?

**Comment by dougwilson** [comment]
Hi! I mean, this is an Express module, not a Koa module. Even then, this module can only access the objects you are passing in as req/res; if you need to pass something different for Koa, then provide the right objects.

Also, you can easily define your own tokens (see readme for instructions). You can redefine the remote-addr token to work with whatever Koa provides.
