### ISSUE TITLE
Tools to view the log generated by morgan

### ISSUE THREAD

**Issue by qlqllu** [expressjs/morgan#85]
Sorry, I think this issue is not about morgan, but I want to get some tips from here.
It's very good to use morgan to log HTTP access log, but how to view the logs? Which tool/framework do you use to view the log?

Thanks!

**Comment by dougwilson** [comment]
Hi! If you use one of the listed Apache formats to create your logs, then a lot of standard log viewers can analyze your logs. AWStats (http://www.awstats.org/) is a very popular access log analyzer.
