### ISSUE TITLE
Support for local timezone

### ISSUE THREAD

**Issue by yashgt** [expressjs/morgan#91]
Hi,

The :date token causes the date to be printed in UTC. Can you add a new token :local-date that will print it in local timezone? 

Regards,
Yash

**Comment by dougwilson** [comment]
Hi! We won't be adding the functionality due to various prior discussions, but you're welcome to add it to your own instance. Simply create the token in your code; instructions at https://github.com/expressjs/morgan/blob/master/README.md#creating-new-tokens
