### ISSUE TITLE
include "typings" field in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [expressjs/morgan#92]
Now that the TS compiler supports module [resolution](https://github.com/Microsoft/TypeScript/issues/2338) via node, it would be nice not to use TSD to install the typing but instead have them included with the npm package.

**Comment by dougwilson** [comment]
We don't have any typings. What would we put in the field?

**Comment by rolandjitsu** [comment]
@dougwilson I am trying to figure that out myself ... It should be documented somewhere in the Wiki for TypeScript.

No, you do not have typings, but the community has created them on TSD (DefinitelyTyped) to help with TS development. And it would be nice to provide that with your package.

I'll investigate further to see how do you actually do it.

**Comment by dougwilson** [comment]
Thanks! I haven't used TypeScript and have no idea how it works (and not really interested in learning it or even have the time to). I'm open to adding this, but it would have to be something completely contributed by you and part of the contribution would have to also update the CI to ensure that the typings are always correct and do not become out of date as we alter the API in some fashion.

**Comment by dougwilson** [comment]
Hi @rolandjitsu , I'm' going to close this for now, as there doesn't seem to be any interest in contributing these, as I have not seen a further response or a pull request.
