### ISSUE TITLE
Date format is not work

### ISSUE THREAD

**Issue by Trinea** [expressjs/morgan#95]
```js
exports.token('date', function(){
  return new Date().toUTCString();
});
```

is not work for

##### :date[format]

The current date and time in UTC. The available formats are:

  - `clf` for the common log format (`"10/Oct/2000:13:55:36 +0000"`)
  - `iso` for the common ISO 8601 date time format (`2000-10-10T13:55:36.000Z`)
  - `web` for the common RFC 1123 date time format (`Tue, 10 Oct 2000 13:55:36 GMT`)

**Comment by dougwilson** [comment]
Hi @Trinea, I'm happy to help! Can you elaborate on the issue you are having? To get a particular format, you just need to pass in a format string to the morgan middleware factory. For example, to get the "web" format with the method and URL requested:
```js
app.use(morgan(':date[web] :method :url'))
```

If that does not answer your question, please let me know!

**Comment by Trinea** [comment]
There is no ouput difference between
```
app.use(morgan(':date :method :url'))
app.use(morgan(':date[web] :method :url'))
app.use(morgan(':date[iso] :method :url'))
app.use(morgan(':date[clf] :method :url'))
```
It's always GMT date format like this:
```
Tue Jan 19 2016 10:33:23 GMT+0800 (CST)
```
You can try.

**Comment by dougwilson** [comment]
@Trinea, that is expected if you are not using the version of the documentation you are reading. The different formats were not added until version 1.5.0 of this module, so using any version prior to 1.5.0 will result in the same format, as they do not read the arguments. In fact, I now notice that the piece of the source code you copied above is from a pre-1.5.0 version of this module. You can see the current source code is the following: https://github.com/expressjs/morgan/blob/1.6.1/index.js#L246-L257

Using the current version 1.6.1, I have the following output:
```
$ npm i express morgan
morgan@1.6.1 node_modules\morgan
├── basic-auth@1.0.3
├── on-headers@1.0.1
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
└── debug@2.2.0 (ms@0.7.1)

express@4.13.3 node_modules\express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.2
├── cookie@0.1.3
├── fresh@0.3.0
├── vary@1.0.1
├── parseurl@1.3.1
├── range-parser@1.0.3
├── path-to-regexp@0.1.7
├── content-type@1.0.1
├── etag@1.7.0
├── content-disposition@0.5.0
├── qs@4.0.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── debug@2.2.0 (ms@0.7.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.10 (media-typer@0.3.0, mime-types@2.1.9)
├── serve-static@1.10.1 (escape-html@1.0.3, send@0.13.1)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.9)

$ cat app.js
var express = require('express')
var morgan = require('morgan')

var app = express()

app.use(morgan(':date :method :url'))
app.use(morgan(':date[web] :method :url'))
app.use(morgan(':date[iso] :method :url'))
app.use(morgan(':date[clf] :method :url'))

app.get('/', function (req, res) {
  res.send('hello, world!')
})

app.listen(4000)

$ node app.js &
[1] 17440

$ curl http://127.0.0.1:4000/
hello, world!
Tue, 19 Jan 2016 02:51:29 GMT GET /
Tue, 19 Jan 2016 02:51:29 GMT GET /
2016-01-19T02:51:29.704Z GET /
19/Jan/2016:02:51:29 +0000 GET /
```

We include the `README.md` file on the installation of the module, so if you are not sure what features your installed version supports, you can always load the `README.md` file off your disk.

**Comment by Trinea** [comment]
I have updated the version to 1.6.1 of morgan, It's ok now, thank you very much.

**Comment by dougwilson** [comment]
Good to hear! Glad that was the issue :) Sorry I didn't really notice from the snippet you originally posted.
