### ISSUE TITLE
How to generate log file with header name with date

### ISSUE THREAD

**Issue by mouryaamit** [expressjs/morgan#96]
Hi,
      I am currently able to use 
```
var accessLogStream = FileStreamRotator.getStream({
    filename: logDirectory + '/access-%DATE%.log',
    frequency: 'daily',
    verbose: true,
    date_format: "YYYY-MM-DD"
});
```
which generate file as ***access-2016-01-26***
Now I want to generate file name as ***access-2016-01-26-Inst-1*** where **Inst-1** comes in header of request with header name **Inst-Id**.  
Since I have many institution using same servers I need to generate separate the logs as
***access-2016-01-26-Inst-1***
***access-2016-01-26-Inst-2***

**Comment by dougwilson** [comment]
Hi! This would probably be a question for the `file-stream-rotator` npm module, as those file name are computed by that module.

Not sure if there is a way for that module to actually generate file names based on what we're writing to the stream, though. You may have to either use a module to multiplex multiple streams or use multiple `morgan` instances.

An example of using multiple `morgan` instances would be the following:
```js
var morganInstances = Object.create(null);

app.use(function (req, res, next) {
  var inst = req.headers['x-instance-id'];
});

function getMorganInstance(id) {
  if (!morganInstances[id]) {
    morganInstances[id] = createMorganInstance(id);
  }

  return morganInstances[id];
}

function createMorganInstance(id) {
  return morgan('apache', {
    stream: createMorganInstanceStream(id)
  });
}

function createMorganInstanceStream(id) {
  return FileStreamRotator.getStream({
    filename: logDirectory + '/access-%DATE%-Inst-' + id + '.log',
    frequency: 'daily',
    verbose: true,
    date_format: "YYYY-MM-DD"
  });
}
```

**Comment by mouryaamit** [comment]
I used the same with koa.js
it is able to create the file but not loging anything inside that

**Comment by dougwilson** [comment]
Hi @mouryaamit, I'm not really sure what you are saying. Can you try to describe it again? Perhaps provide specific code, how to cal the code, and how it's not meeting your expectations?
